// data-powers.js

const powers = [
    /* Offensive */
    { name: "Super Strength", icon: "fitness_center", type: ["Brawler", "Tank", "Warrior"] },
    { name: "Energy Blasts (Force/Kinetic)", icon: "bolt", type: ["Blaster", "Elementalist"] },
    { name: "Energy Blasts (Heat/Fire)", icon: "local_fire_department", type: ["Blaster", "Elementalist"] },
    { name: "Energy Blasts (Cold/Ice)", icon: "ac_unit", type: ["Blaster", "Elementalist"] },
    { name: "Energy Blasts (Electric)", icon: "flash_on", type: ["Blaster", "Elementalist"] },
    { name: "Energy Blasts (Light/Radiant)", icon: "wb_sunny", type: ["Blaster", "Mystic", "Paladin"] },
    { name: "Energy Blasts (Shadow/Dark)", icon: "dark_mode", type: ["Blaster", "Mystic", "Rogue", "Warlock"] },
    { name: "Sonic Scream/Blast", icon: "volume_up", type: ["Blaster", "Controller"] },
    { name: "Weapon Summoning (Energy/Physical)", icon: "construction", type: ["Warrior", "Mystic", "Gadgeteer"] },
    { name: "Acid/Poison Generation/Projection", icon: "science", type: ["Blaster", "Rogue", "Controller"] },
    { name: "Explosion Generation", icon: "bomb", type: ["Blaster"] },
    /* Defensive/Utility */
    { name: "Super Speed", icon: "speed", type: ["Speedster", "Rogue"] },
    { name: "Flight (Winged/Propulsion/Levitation)", icon: "flight", type: ["Speedster", "Blaster", "Mystic"] },
    { name: "Regeneration (Minor/Major)", icon: "healing", type: ["Tank", "Brawler"] },
    { name: "Force Field Generation", icon: "shield", type: ["Tank", "Controller", "Support"] },
    { name: "Enhanced Durability/Invulnerability", icon: "security", type: ["Tank", "Brawler", "Warrior"] },
    { name: "Invisibility/Camouflage", icon: "visibility_off", type: ["Infiltrator", "Rogue"] },
    { name: "Intangibility/Phasing", icon: "blur_on", type: ["Infiltrator", "Speedster"] },
    { name: "Teleportation (Short/Long Range)", icon: "swap_horiz", type: ["Speedster", "Infiltrator", "Mystic"] },
    { name: "Enhanced Senses (All/Specific)", icon: "hearing", type: ["Infiltrator", "Marksman", "Druid"] },
    { name: "Wall-Crawling/Adhesion", icon: "vertical_align_top", type: ["Infiltrator", "Rogue"] },
    { name: "Danger Sense/Precognitive Reflexes", icon: "crisis_alert", type: ["Any"] },
    { name: "Adaptation (Environmental/Threat)", icon: "sync_alt", type: ["Tank", "Shapeshifter"] },
    /* Mental/Mystical */
    { name: "Telekinesis", icon: "psychology", type: ["Psychic", "Controller", "Mystic"] },
    { name: "Telepathy (Read/Project/Link)", icon: "wifi_tethering", type: ["Psychic", "Controller", "Infiltrator"] },
    { name: "Illusion Casting", icon: "movie_filter", type: ["Mystic", "Controller", "Rogue", "Bard"] },
    { name: "Magic/Sorcery (Elemental/Arcane/Divine)", icon: "auto_fix_high", type: ["Mystic", "Sorcerer", "Warlock", "Paladin"] },
    { name: "Precognition (Vague/Specific)", icon: "update", type: ["Psychic", "Mystic", "Support"] },
    { name: "Mind Control/Suggestion", icon: "neurology", type: ["Psychic", "Controller", "Bard", "Warlock"] },
    { name: "Astral Projection", icon: "travel_explore", type: ["Mystic", "Psychic"] },
    { name: "Necromancy (Limited)", icon: "skull", type: ["Mystic", "Warlock"] },
    /* Control/Manipulation */
    { name: "Shapeshifting (Animal/Humanoid/Object)", icon: "transform", type: ["Shapeshifter", "Druid", "Infiltrator"] },
    { name: "Elemental Control (Fire)", icon: "local_fire_department", type: ["Elementalist", "Mystic"] },
    { name: "Elemental Control (Water/Ice)", icon: "water_drop", type: ["Elementalist", "Mystic"] },
    { name: "Elemental Control (Earth/Metal)", icon: "landscape", type: ["Elementalist", "Tank"] },
    { name: "Elemental Control (Air/Weather)", icon: "air", type: ["Elementalist", "Speedster"] },
    { name: "Technopathy/Cyberpathy", icon: "memory", type: ["Gadgeteer", "Artificer", "Controller"] },
    { name: "Magnetism Control", icon: "settings_input_component", type: ["Controller", "Elementalist"] },
    { name: "Gravity Manipulation", icon: "public", type: ["Controller", "Tank"] },
    { name: "Plant Control/Chlorokinesis", icon: "forest", type: ["Druid", "Controller", "Elementalist"] },
    { name: "Animal Communication/Control", icon: "pets", type: ["Druid", "Support", "Summoner"] },
    { name: "Sound Manipulation/Absorption", icon: "surround_sound", type: ["Controller", "Support"] },
    { name: "Light Manipulation (Hard Light)", icon: "highlight", type: ["Controller", "Blaster", "Mystic"] },
    { name: "Shadow Manipulation/Travel", icon: "nights_stay", type: ["Infiltrator", "Rogue", "Mystic", "Warlock"] },
    /* Body Manipulation */
    { name: "Elasticity/Plasticity", icon: "commit", type: ["Shapeshifter", "Brawler"] },
    { name: "Size Manipulation (Grow/Shrink)", icon: "aspect_ratio", type: ["Shapeshifter", "Tank", "Infiltrator"] },
    { name: "Density Control (Increase/Decrease)", icon: "compress", type: ["Tank", "Infiltrator"] },
    { name: "Bone/Claw/Spike Generation", icon: "cut", type: ["Brawler", "Warrior"] },
    { name: "Biological Manipulation (Self)", icon: "biotech", type: ["Shapeshifter", "Tank"] },
    { name: "Duplication (Self)", icon: "control_point_duplicate", type: ["Controller", "Infiltrator"] },
    { name: "Pheromone Control", icon: "hive", type: ["Controller", "Bard", "Infiltrator"] },
    /* Support/Other */
    { name: "Healing (Self/Others)", icon: "medical_services", type: ["Healer/Support", "Mystic", "Paladin"] },
    { name: "Power Augmentation/Granting", icon: "trending_up", type: ["Support", "Mystic"] },
    { name: "Power Nullification/Dampening", icon: "block", type: ["Controller", "Support", "Tank"] },
    { name: "Summoning (Creatures/Objects/Elementals)", icon: "group_add", type: ["Summoner", "Mystic", "Warlock"] },
    { name: "Probability Manipulation (Luck/Jinx)", icon: "casino", type: ["Controller", "Rogue", "Bard"] },
    { name: "Portal Creation", icon: "adjust", type: ["Mystic", "Speedster"] },
    { name: "Omnilingualism", icon: "translate", type: ["Support", "Infiltrator", "Psychic"] },
    /* Drawbacks / Weaknesses */
    { name: "Power Instability/Backlash", icon: "warning", type: ["Drawback"], drawback: true },
    { name: "Energy Drain (Requires Touch/Proximity)", icon: "battery_alert", type: ["Drawback", "Brawler"], drawback: true },
    { name: "Vulnerability (Specific Element/Material/Energy)", icon: "report", type: ["Drawback"], drawback: true },
    { name: "Uncontrolled Power Surges", icon: "error", type: ["Drawback"], drawback: true },
    { name: "Horrific/Unsettling Appearance", icon: "sentiment_very_dissatisfied", type: ["Drawback"], drawback: true },
    { name: "Constant Pain/Discomfort", icon: "sick", type: ["Drawback"], drawback: true },
    { name: "Severe Allergy (Common Substance)", icon: "allergy", type: ["Drawback"], drawback: true },
    { name: "Power Negation Field (Self)", icon: "signal_cellular_off", type: ["Drawback"], drawback: true },
    { name: "Mental Instability/Voices", icon: "psychiatry", type: ["Drawback", "Psychic"], drawback: true },
    { name: "Sunlight/Specific Condition Weakness", icon: "wb_twilight", type: ["Drawback"], drawback: true },
    { name: "Power Requires Fuel/Charge/Emotion", icon: "battery_charging_full", type: ["Drawback"], drawback: true },
    { name: "Mutation/Degeneration Risk", icon: "coronavirus", type: ["Drawback"], drawback: true },
    { name: "Noticeable Tell/Side Effect", icon: "visibility", type: ["Drawback"], drawback: true },
    { name: "Phobia (Specific/Crippling)", icon: "panic", type: ["Drawback"], drawback: true },
    { name: "Code of Honor/Restriction", icon: "gavel", type: ["Drawback"], drawback: true },
    { name: "Social Stigma/Outcast", icon: "group_off", type: ["Drawback"], drawback: true },
    { name: "Dependency (Substance/Person/Object)", icon: "pill", type: ["Drawback"], drawback: true },
    { name: "Limited Power Usage (Charges/Time)", icon: "hourglass_empty", type: ["Drawback"], drawback: true },
    { name: "Emotional Power Trigger (Unreliable)", icon: "sentiment_neutral", type: ["Drawback"], drawback: true },
];