// js/data.js
export const artifactTypes = ["Staff", "Wand"];
export const artifactIcons = { Staff: "fa-staff", Wand: "fa-magic-wand-sparkles" };
export const defaultIcon = "fa-gem";

export const standoutFeatures = [
  "a pattern of thorns", "mysterious inscribings", "an ornate handle", "a unique texture", "glowing runes",
  "shimmering rings", "carved eyes", "a row of jagged teeth"
];

export const adjectives = [
  "Arcane", "Mystic", "Ethereal", "Celestial", "Shadowy", "Ancient", "Enchanted",
  "Runed", "Whispering", "Luminous", "Resonant", "Harmonious", "Astral", "Eldritch",
  "Prismatic", "Veiled", "Chaotic", "Boundless", "Ephemeral", "Forbidden",
  "Tempestuous", "Shimmering", "Soggy", "Awkward", "Gassy", "Clumsy", "Quacking",
  "Snazzy", "Dorky", "Jiggling", "Funky", "Cheesy", "Spicy", "Wobbly", "Flatulent",
  "Overcaffeinated", "Itchy", "Goopy", "Bedazzled", "Slippery", "Sassy",
  "Blindingly Glittery", "Lumpy", "Mediocre", "Confused", "Unhinged", "Perpetually Damp",
  "Ridiculously Bright", "Tacky", "Overdramatic", "Overly Sincere", "Chronically Embarrassed",
  "Super Annoying", "Excessively Chatty", "Slightly Crooked"
];

export const materials = [
  "Oak", "Ebony", "Rosewood", "Ashwood", "Birch", "Maple", "Willow", "Pine", "Mahogany",
  "Yew", "Silver", "Gold", "Electrum", "Platinum", "Mithril", "Adamantine", "Copper",
  "Bronze", "Orichalcum", "Quicksilver", "Crystal", "Sapphire", "Ruby", "Emerald",
  "Amethyst", "Topaz", "Moonstone", "Sunstone", "Obsidian", "Jade", "Onyx", "Opal",
  "Peridot", "Garnet", "Aquamarine", "Spinel", "Zircon", "Starmetal", "Petrified Wood",
  "Living Wood", "Frozen Tears", "Phoenix Feather", "Unicorn Horn", "Astral Shard",
  "Void Stone", "Dreamweave", "Heartwood", "Soulsteel", "Whisperwood", "Emberglass",
  "Shadowsilk", "Celestium", "Aetherium", "Etherglass", "Bloodstone", "Driftstone",
  "Duskwood", "Frostwood", "Luminite", "Nethercrystal", "Arcane Resin", "Spellglass",
  "Eclipsium", "Twilight Ore",
  "Paper Mache", "Cheesecloth", "Duct Tape", "Cardboard", "Bubble Wrap", "Styrofoam", "Rubber",
  "Old Shoe Leather", "Goblin Earwax", "Unicorn Farts", "Chicken Bone", "Recycled Goblin Toenails",
  "Melted Candles", "Beeswax", "Sock Fabric", "Mossy Pebbles", "Belly Button Lint", "Petrified Bread",
  "Glitter Glue", "Toenail Clippings", "Worn-Out Sandals", "Discarded Toothpicks"
];

export const spellLists = {
  Abjuration: [
    { name: "Blade Ward", level: 0 },
    { name: "Resistance", level: 0 },
    { name: "Spare the Dying", level: 0 },
    { name: "Alarm", level: 1 },
    { name: "Armor of Agathys", level: 1 },
    { name: "Ceremony", level: 1 },
    { name: "Detect Magic", level: 1 },
    { name: "Protection from Evil and Good", level: 1 },
    { name: "Protection from Poison", level: 1 },
    { name: "Sanctuary", level: 1 },
    { name: "Shield", level: 1 },
    { name: "Arcane Lock", level: 2 },
    { name: "Blur", level: 2 },
    { name: "Calm Emotions", level: 2 },
    { name: "Darkness", level: 2 },
    { name: "Gust of Wind", level: 2 },
    { name: "Magic Weapon", level: 2 },
    { name: "Nystul's Magic Aura", level: 2 },
    { name: "Protection from Energy", level: 2 },
    { name: "Ray of Enfeeblement", level: 2 },
    { name: "Warding Bond", level: 2 },
    { name: "Aura of Vitality", level: 3 },
    { name: "Counterspell", level: 3 },
    { name: "Dispel Magic", level: 3 },
    { name: "Glyph of Warding", level: 3 },
    { name: "Magic Circle", level: 3 },
    { name: "Melf's Minute Meteors", level: 3 },
    { name: "Remove Curse", level: 3 },
    { name: "Revivify", level: 3 },
    { name: "Aura of Life", level: 4 },
    { name: "Banishment", level: 4 },
    { name: "Death Ward", level: 4 },
    { name: "Dimension Door", level: 4 },
    { name: "Freedom of Movement", level: 4 },
    { name: "Greater Invisibility", level: 4 },
    { name: "Leomund's Secret Chest", level: 4 },
    { name: "Otiluke's Resilient Sphere", level: 4 },
    { name: "Private Sanctum", level: 4 },
    { name: "Stoneskin", level: 4 },
    { name: "Antilife Shell", level: 5 },
    { name: "Circle of Power", level: 5 },
    { name: "Dispel Evil and Good", level: 5 },
    { name: "Geas", level: 5 },
    { name: "Holy Weapon", level: 5 },
    { name: "Wall of Force", level: 5 },
    { name: "Arcane Gate", level: 6 },
    { name: "Forbiddance", level: 6 },
    { name: "Globe of Invulnerability", level: 6 },
    { name: "Guards and Wards", level: 6 },
    { name: "Heal", level: 6 },
    { name: "Magic Jar", level: 6 },
    { name: "Planar Ally", level: 6 },
    { name: "Prismatic Spray", level: 6 },
    { name: "True Seeing", level: 6 },
    { name: "Word of Recall", level: 6 },
    { name: "Conjure Celestial", level: 7 },
    { name: "Divine Word", level: 7 },
    { name: "Etherealness", level: 7 },
    { name: "Plane Shift", level: 7 },
    { name: "Prismatic Wall", level: 7 },
    { name: "Symbol", level: 7 },
    { name: "Antimagic Field", level: 8 },
    { name: "Control Weather", level: 8 },
    { name: "Holy Aura", level: 8 },
    { name: "Mind Blank", level: 8 },
    { name: "Imprisonment", level: 9 },
    { name: "Invulnerability", level: 9 },
    { name: "Time Stop", level: 9 },
    { name: "Wish", level: 9 }
  ],
  Conjuration: [
    { name: "Acid Splash", level: 0 },
    { name: "Create Bonfire", level: 0 },
    { name: "Frostbite", level: 0 },
    { name: "Magic Stone", level: 0 },
    { name: "Poison Spray", level: 0 },
    { name: "Produce Flame", level: 0 },
    { name: "Ray of Frost", level: 0 },
    { name: "Shillelagh", level: 0 },
    { name: "Thunderclap", level: 0 },
    { name: "Animal Friendship", level: 1 },
    { name: "Beast Bond", level: 1 },
    { name: "Bless", level: 1 },
    { name: "Burning Hands", level: 1 },
    { name: "Catapult", level: 1 },
    { name: "Cause Fear", level: 1 },
    { name: "Color Spray", level: 1 },
    { name: "Cure Wounds", level: 1 },
    { name: "Detect Poison and Disease", level: 1 },
    { name: "Disguise Self", level: 1 },
    { name: "Entangle", level: 1 },
    { name: "Expeditious Retreat", level: 1 },
    { name: "False Life", level: 1 },
    { name: "Find Familiar", level: 1 },
    { name: "Fog Cloud", level: 1 },
    { name: "Goodberry", level: 1 },
    { name: "Healing Word", level: 1 },
    { name: "Hex", level: 1 },
    { name: "Hunter's Mark", level: 1 },
    { name: "Ice Knife", level: 1 },
    { name: "Illusory Script", level: 1 },
    { name: "Jump", level: 1 },
    { name: "Longstrider", level: 1 },
    { name: "Mage Armor", level: 1 },
    { name: "Magic Missile", level: 1 },
    { name: "Protection from Evil and Good", level: 1 },
    { name: "Purify Food and Drink", level: 1 },
    { name: "Sanctuary", level: 1 },
    { name: "Shield of Faith", level: 1 },
    { name: "Sleep", level: 1 },
    { name: "Speak with Animals", level: 1 },
    { name: "Tenser's Floating Disk", level: 1 },
    { name: "Thunderwave", level: 1 },
    { name: "Unseen Servant", level: 1 },
    { name: "Acid Arrow", level: 2 },
    { name: "Aid", level: 2 },
    { name: "Animal Messenger", level: 2 },
    { name: "Barkskin", level: 2 },
    { name: "Blindness/Deafness", level: 2 },
    { name: "Cloud of Daggers", level: 2 },
    { name: "Continual Flame", level: 2 },
    { name: "Create or Destroy Water", level: 2 },
    { name: "Darkness", level: 2 },
    { name: "Darkvision", level: 2 },
    { name: "Dust of Disappearance", level: 2 },
    { name: "Earthbind", level: 2 },
    { name: "Enlarge/Reduce", level: 2 },
    { name: "Find Steed", level: 2 },
    { name: "Flaming Sphere", level: 2 },
    { name: "Gentle Repose", level: 2 },
    { name: "Gust of Wind", level: 2 },
    { name: "Healing Spirit", level: 2 },
    { name: "Hold Person", level: 2 },
    { name: "Invisibility", level: 2 },
    { name: "Knock", level: 2 },
    { name: "Lesser Restoration", level: 2 },
    { name: "Locate Animals or Plants", level: 2 },
    { name: "Locate Object", level: 2 },
    { name: "Magic Weapon", level: 2 },
    { name: "Maximilian's Earthen Grasp", level: 2 },
    { name: "Misty Step", level: 2 },
    { name: "Moonbeam", level: 2 },
    { name: "Pass without Trace", level: 2 },
    { name: "Prayer of Healing", level: 2 },
    { name: "Protection from Poison", level: 2 },
    { name: "Ray of Enfeeblement", level: 2 },
    { name: "Rope Trick", level: 2 },
    { name: "Scorching Ray", level: 2 },
    { name: "See Invisibility", level: 2 },
    { name: "Shatter", level: 2 },
    { name: "Spider Climb", level: 2 },
    { name: "Spike Growth", level: 2 },
    { name: "Summon Beast", level: 2 },
    { name: "Summon Fey Spirit", level: 2 },
    { name: "Summon Shadowspawn", level: 2 },
    { name: "Summon Undead", level: 2 },
    { name: "Web", level: 2 },
    { name: "Zone of Truth", level: 2 },
    { name: "Animate Dead", level: 3 },
    { name: "Aura of Vitality", level: 3 },
    { name: "Beacon of Hope", level: 3 },
    { name: "Bestow Curse", level: 3 },
    { name: "Call Lightning", level: 3 },
    { name: "Clairvoyance", level: 3 },
    { name: "Conjure Animals", level: 3 },
    { name: "Conjure Barrage", level: 3 },
    { name: "Conjure Minor Elementals", level: 3 },
    { name: "Conjure Woodland Beings", level: 3 },
    { name: "Create Food and Water", level: 3 },
    { name: "Daylight", level: 3 },
    { name: "Dispel Magic", level: 3 },
    { name: "Elemental Weapon", level: 3 },
    { name: "Feign Death", level: 3 },
    { name: "Fireball", level: 3 },
    { name: "Flame Arrows", level: 3 },
    { name: "Fly", level: 3 },
    { name: "Gaseous Form", level: 3 },
    { name: "Glyph of Warding", level: 3 },
    { name: "Haste", level: 3 },
    { name: "Hypnotic Pattern", level: 3 },
    { name: "Leomund's Tiny Hut", level: 3 },
    { name: "Life Transference", level: 3 },
    { name: "Lightning Bolt", level: 3 },
    { name: "Magic Circle", level: 3 },
    { name: "Mass Healing Word", level: 3 },
    { name: "Melf's Minute Meteors", level: 3 },
    { name: "Phantom Steed", level: 3 },
    { name: "Plant Growth", level: 3 },
    { name: "Protection from Energy", level: 3 },
    { name: "Remove Curse", level: 3 },
    { name: "Revivify", level: 3 },
    { name: "Sending", level: 3 },
    { name: "Sleet Storm", level: 3 },
    { name: "Speak with Plants", level: 3 },
    { name: "Spirit Guardians", level: 3 },
    { name: "Stinking Cloud", level: 3 },
    { name: "Summon Aberration", level: 3 },
    { name: "Summon Celestial Spirit", level: 3 },
    { name: "Summon Construct", level: 3 },
    { name: "Summon Elemental", level: 3 },
    { name: "Summon Fiend", level: 3 },
    { name: "Summon Draconic Spirit", level: 3 },
    { name: "Summon Undead", level: 3 },
    { name: "Thunder Step", level: 3 },
    { name: "Tiny Servant", level: 3 },
    { name: "Tongues", level: 3 },
    { name: "Vampiric Touch", level: 3 },
    { name: "Wall of Water", level: 3 },
    { name: "Water Breathing", level: 3 },
    { name: "Water Walk", level: 3 },
    { name: "Wind Wall", level: 3 },
    { name: "Aura of Life", level: 4 },
    { name: "Banishment", level: 4 },
    { name: "Blight", level: 4 },
    { name: "Charm Monster", level: 4 },
    { name: "Compulsion", level: 4 },
    { name: "Conjure Elemental", level: 4 },
    { name: "Conjure Fey", level: 4 },
    { name: "Control Water", level: 4 },
    { name: "Death Ward", level: 4 },
    { name: "Dimension Door", level: 4 },
    { name: "Divination", level: 4 },
    { name: "Dominate Beast", level: 4 },
    { name: "Evard's Black Tentacles", level: 4 },
    { name: "Fabricate", level: 4 },
    { name: "Find Greater Steed", level: 4 },
    { name: "Fire Shield", level: 4 },
    { name: "Freedom of Movement", level: 4 },
    { name: "Giant Insect", level: 4 },
    { name: "Greater Invisibility", level: 4 },
    { name: "Guardian of Faith", level: 4 },
    { name: "Hallucinatory Terrain", level: 4 },
    { name: "Ice Storm", level: 4 },
    { name: "Leomund's Secret Chest", level: 4 },
    { name: "Locate Creature", level: 4 },
    { name: "Mordenkainen's Private Sanctum", level: 4 },
    { name: "Otiluke's Resilient Sphere", level: 4 },
    { name: "Polymorph", level: 4 },
    { name: "Private Sanctum", level: 4 },
    { name: "Rauryk's Telepathic Bond", level: 4 },
    { name: "Resilient Sphere", level: 4 },
    { name: "Secret Chest", level: 4 },
    { name: "Sickening Radiance", level: 4 },
    { name: "Stoneskin", level: 4 },
    { name: "Summon Greater Demon", level: 4 },
    { name: "Summon Shadow Spirit", level: 4 },
    { name: "Summon Undead Spirit", level: 4 },
    { name: "Teleportation Circle", level: 4 },
    { name: "Wall of Fire", level: 4 },
    { name: "Animate Objects", level: 5 },
    { name: "Antilife Shell", level: 5 },
    { name: "Awaken", level: 5 },
    { name: "Circle of Power", level: 5 },
    { name: "Cloudkill", level: 5 },
    { name: "Commune", level: 5 },
    { name: "Conjure Celestial", level: 5 },
    { name: "Conjure Elemental", level: 5 },
    { name: "Conjure Volley", level: 5 },
    { name: "Contact Other Plane", level: 5 },
    { name: "Control Winds", level: 5 },
    { name: "Creation", level: 5 },
    { name: "Dawn", level: 5 },
    { name: "Destructive Wave", level: 5 },
    { name: "Dispel Evil and Good", level: 5 },
    { name: "Dominate Person", level: 5 },
    { name: "Dream", level: 5 },
    { name: "Flame Strike", level: 5 },
    { name: "Geas", level: 5 },
    { name: "Greater Restoration", level: 5 },
    { name: "Hallow", level: 5 },
    { name: "Hold Monster", level: 5 },
    { name: "Holy Weapon", level: 5 },
    { name: "Insect Plague", level: 5 },
    { name: "Legend Lore", level: 5 },
    { name: "Mass Cure Wounds", level: 5 },
    { name: "Mass Healing Word", level: 5 },
    { name: "Misty Step", level: 5 },
    { name: "Modify Memory", level: 5 },
    { name: "Planar Binding", level: 5 },
    { name: "Raise Dead", level: 5 },
    { name: "Reincarnate", level: 5 },
    { name: "Rope Trick", level: 5 },
    { name: "Scrying", level: 5 },
    { name: "Seeming", level: 5 },
    { name: "Skill Empowerment", level: 5 },
    { name: "Steel Wind Strike", level: 5 },
    { name: "Summon Aberration", level: 5 },
    { name: "Summon Celestial Spirit", level: 5 },
    { name: "Summon Construct", level: 5 },
    { name: "Summon Elemental", level: 5 },
    { name: "Summon Fiend", level: 5 },
    { name: "Summon Greater Demon", level: 5 },
    { name: "Summon Shadowspawn", level: 5 },
    { name: "Summon Undead", level: 5 },
    { name: "Teleportation Circle", level: 5 },
    { name: "Wall of Force", level: 5 },
    { name: "Wall of Stone", level: 5 },
    { name: "Arcane Gate", level: 6 },
    { name: "Blade Barrier", level: 6 },
    { name: "Chain Lightning", level: 6 },
    { name: "Circle of Death", level: 6 },
    { name: "Conjure Fey", level: 6 },
    { name: "Conjure Woodland Beings", level: 6 },
    { name: "Create Undead", level: 6 },
    { name: "Disintegrate", level: 6 },
    { name: "Drawmij's Instant Summons", level: 6 },
    { name: "Find the Path", level: 6 },
    { name: "Forbiddance", level: 6 },
    { name: "Globe of Invulnerability", level: 6 },
    { name: "Guards and Wards", level: 6 },
    { name: "Heal", level: 6 },
    { name: "Magic Jar", level: 6 },
    { name: "Mass Suggestion", level: 6 },
    { name: "Move Earth", level: 6 },
    { name: "Planar Ally", level: 6 },
    { name: "Programmed Illusion", level: 6 },
    { name: "Raise Dead", level: 6 },
    { name: "Sunbeam", level: 6 },
    { name: "Symbol", level: 6 },
    { name: "Teleportation Circle", level: 6 },
    { name: "Transport via Plants", level: 6 },
    { name: "True Seeing", level: 6 },
    { name: "Wall of Ice", level: 6 },
    { name: "Word of Recall", level: 6 },
    { name: "Conjure Celestial", level: 7 },
    { name: "Conjure Elemental", level: 7 },
    { name: "Conjure Fey", level: 7 },
    { name: "Conjure Woodland Beings", level: 7 },
    { name: "Create Undead", level: 7 },
    { name: "Divine Word", level: 7 },
    { name: "Etherealness", level: 7 },
    { name: "Finger of Death", level: 7 },
    { name: "Fire Storm", level: 7 },
    { name: "Plane Shift", level: 7 },
    { name: "Prismatic Spray", level: 7 },
    { name: "Project Image", level: 7 },
    { name: "Regenerate", level: 7 },
    { name: "Resurrection", level: 7 },
    { name: "Reverse Gravity", level: 7 },
    { name: "Simulacrum", level: 7 },
    { name: "Teleport", level: 7 },
    { name: "Temple of the Gods", level: 7 },
    { name: "Wall of Force", level: 7 },
    { name: "Word of Recall", level: 7 },
    { name: "Animal Shapes", level: 8 },
    { name: "Antimagic Field", level: 8 },
    { name: "Clone", level: 8 },
    { name: "Control Weather", level: 8 },
    { name: "Create Undead", level: 8 },
    { name: "Earthquake", level: 8 },
    { name: "Holy Aura", level: 8 },
    { name: "Incendiary Cloud", level: 8 },
    { name: "Mind Blank", level: 8 },
    { name: "Planar Ally", level: 8 },
    { name: "Power Word Stun", level: 8 },
    { name: "Sunburst", level: 8 },
    { name: "Teleport", level: 8 },
    { name: "Tsunami", level: 8 },
    { name: "Wall of Ice", level: 8 },
    { name: "Astral Projection", level: 9 },
    { name: "Conjure Animals", level: 9 },
    { name: "Conjure Celestial", level: 9 },
    { name: "Conjure Elemental", level: 9 },
    { name: "Conjure Fey", level: 9 },
    { name: "Conjure Woodland Beings", level: 9 },
    { name: "Gate", level: 9 },
    { name: "Mass Heal", level: 9 },
    { name: "Meteor Swarm", level: 9 },
    { name: "Power Word Kill", level: 9 },
    { name: "Prismatic Wall", level: 9 },
    { name: "Shapechange", level: 9 },
    { name: "Storm of Vengeance", level: 9 },
    { name: "Time Stop", level: 9 },
    { name: "True Polymorph", level: 9 },
    { name: "Wish", level: 9 }
  ],
  Divination: [
    { name: "Guidance", level: 0 },
    { name: "Message", level: 0 },
    { name: "True Strike", level: 0 },
    { name: "Animal Friendship", level: 1 },
    { name: "Bless", level: 1 },
    { name: "Ceremony", level: 1 },
    { name: "Comprehend Languages", level: 1 },
    { name: "Detect Evil and Good", level: 1 },
    { name: "Detect Magic", level: 1 },
    { name: "Detect Poison and Disease", level: 1 },
    { name: "Detect Thoughts", level: 1 },
    { name: "Find Familiar", level: 1 },
    { name: "Identify", level: 1 },
    { name: "Illusory Script", level: 1 },
    { name: "Speak with Animals", level: 1 },
    { name: "Tenser's Floating Disk", level: 1 },
    { name: "Unseen Servant", level: 1 },
    { name: "Animal Messenger", level: 2 },
    { name: "Augury", level: 2 },
    { name: "Barkskin", level: 2 },
    { name: "Blindness/Deafness", level: 2 },
    { name: "Calm Emotions", level: 2 },
    { name: "Continual Flame", level: 2 },
    { name: "Darkvision", level: 2 },
    { name: "Detect Thoughts", level: 2 },
    { name: "Enhance Ability", level: 2 },
    { name: "Find Steed", level: 2 },
    { name: "Gentle Repose", level: 2 },
    { name: "Gust of Wind", level: 2 },
    { name: "Hold Person", level: 2 },
    { name: "Invisibility", level: 2 },
    { name: "Knock", level: 2 },
    { name: "Lesser Restoration", level: 2 },
    { name: "Locate Animals or Plants", level: 2 },
    { name: "Locate Object", level: 2 },
    { name: "Magic Weapon", level: 2 },
    { name: "Moonbeam", level: 2 },
    { name: "Nystul's Magic Aura", level: 2 },
    { name: "Pass without Trace", level: 2 },
    { name: "Protection from Poison", level: 2 },
    { name: "Ray of Enfeeblement", level: 2 },
    { name: "Rope Trick", level: 2 },
    { name: "See Invisibility", level: 2 },
    { name: "Spider Climb", level: 2 },
    { name: "Spike Growth", level: 2 },
    { name: "Zone of Truth", level: 2 },
    { name: "Animate Dead", level: 3 },
    { name: "Aura of Vitality", level: 3 },
    { name: "Beacon of Hope", level: 3 },
    { name: "Bestow Curse", level: 3 },
    { name: "Clairvoyance", level: 3 },
    { name: "Conjure Animals", level: 3 },
    { name: "Conjure Minor Elementals", level: 3 },
    { name: "Conjure Woodland Beings", level: 3 },
    { name: "Create Food and Water", level: 3 },
    { name: "Daylight", level: 3 },
    { name: "Dispel Magic", level: 3 },
    { name: "Elemental Weapon", level: 3 },
    { name: "Feign Death", level: 3 },
    { name: "Fireball", level: 3 },
    { name: "Flame Arrows", level: 3 },
    { name: "Fly", level: 3 },
    { name: "Gaseous Form", level: 3 },
    { name: "Glyph of Warding", level: 3 },
    { name: "Haste", level: 3 },
    { name: "Hypnotic Pattern", level: 3 },
    { name: "Leomund's Tiny Hut", level: 3 },
    { name: "Life Transference", level: 3 },
    { name: "Lightning Bolt", level: 3 },
    { name: "Magic Circle", level: 3 },
    { name: "Mass Healing Word", level: 3 },
    { name: "Melf's Minute Meteors", level: 3 },
    { name: "Phantom Steed", level: 3 },
    { name: "Plant Growth", level: 3 },
    { name: "Protection from Energy", level: 3 },
    { name: "Remove Curse", level: 3 },
    { name: "Revivify", level: 3 },
    { name: "Sending", level: 3 },
    { name: "Sleet Storm", level: 3 },
    { name: "Speak with Plants", level: 3 },
    { name: "Spirit Guardians", level: 3 },
    { name: "Stinking Cloud", level: 3 },
    { name: "Summon Aberration", level: 3 },
    { name: "Summon Celestial Spirit", level: 3 },
    { name: "Summon Construct", level: 3 },
    { name: "Summon Elemental", level: 3 },
    { name: "Summon Fiend", level: 3 },
    { name: "Summon Draconic Spirit", level: 3 },
    { name: "Summon Undead", level: 3 },
    { name: "Thunder Step", level: 3 },
    { name: "Tiny Servant", level: 3 },
    { name: "Tongues", level: 3 },
    { name: "Vampiric Touch", level: 3 },
    { name: "Wall of Water", level: 3 },
    { name: "Water Breathing", level: 3 },
    { name: "Water Walk", level: 3 },
    { name: "Wind Wall", level: 3 },
    { name: "Aura of Life", level: 4 },
    { name: "Banishment", level: 4 },
    { name: "Blight", level: 4 },
    { name: "Charm Monster", level: 4 },
    { name: "Compulsion", level: 4 },
    { name: "Conjure Elemental", level: 4 },
    { name: "Conjure Fey", level: 4 },
    { name: "Control Water", level: 4 },
    { name: "Death Ward", level: 4 },
    { name: "Dimension Door", level: 4 },
    { name: "Divination", level: 4 },
    { name: "Dominate Beast", level: 4 },
    { name: "Evard's Black Tentacles", level: 4 },
    { name: "Fabricate", level: 4 },
    { name: "Find Greater Steed", level: 4 },
    { name: "Fire Shield", level: 4 },
    { name: "Freedom of Movement", level: 4 },
    { name: "Giant Insect", level: 4 },
    { name: "Greater Invisibility", level: 4 },
    { name: "Guardian of Faith", level: 4 },
    { name: "Hallucinatory Terrain", level: 4 },
    { name: "Ice Storm", level: 4 },
    { name: "Leomund's Secret Chest", level: 4 },
    { name: "Locate Creature", level: 4 },
    { name: "Mordenkainen's Private Sanctum", level: 4 },
    { name: "Otiluke's Resilient Sphere", level: 4 },
    { name: "Polymorph", level: 4 },
    { name: "Private Sanctum", level: 4 },
    { name: "Rauryk's Telepathic Bond", level: 4 },
    { name: "Resilient Sphere", level: 4 },
    { name: "Secret Chest", level: 4 },
    { name: "Sickening Radiance", level: 4 },
    { name: "Stoneskin", level: 4 },
    { name: "Summon Greater Demon", level: 4 },
    { name: "Summon Shadow Spirit", level: 4 },
    { name: "Summon Undead Spirit", level: 4 },
    { name: "Teleportation Circle", level: 4 },
    { name: "Wall of Fire", level: 4 },
    { name: "Animate Objects", level: 5 },
    { name: "Antilife Shell", level: 5 },
    { name: "Awaken", level: 5 },
    { name: "Circle of Power", level: 5 },
    { name: "Cloudkill", level: 5 },
    { name: "Commune", level: 5 },
    { name: "Conjure Celestial", level: 5 },
    { name: "Conjure Elemental", level: 5 },
    { name: "Conjure Volley", level: 5 },
    { name: "Contact Other Plane", level: 5 },
    { name: "Control Winds", level: 5 },
    { name: "Creation", level: 5 },
    { name: "Dawn", level: 5 },
    { name: "Destructive Wave", level: 5 },
    { name: "Dispel Evil and Good", level: 5 },
    { name: "Dominate Person", level: 5 },
    { name: "Dream", level: 5 },
    { name: "Flame Strike", level: 5 },
    { name: "Geas", level: 5 },
    { name: "Greater Restoration", level: 5 },
    { name: "Hallow", level: 5 },
    { name: "Hold Monster", level: 5 },
    { name: "Holy Weapon", level: 5 },
    { name: "Insect Plague", level: 5 },
    { name: "Legend Lore", level: 5 },
    { name: "Mass Cure Wounds", level: 5 },
    { name: "Mass Healing Word", level: 5 },
    { name: "Misty Step", level: 5 },
    { name: "Modify Memory", level: 5 },
    { name: "Planar Binding", level: 5 },
    { name: "Raise Dead", level: 5 },
    { name: "Reincarnate", level: 5 },
    { name: "Rope Trick", level: 5 },
    { name: "Scrying", level: 5 },
    { name: "Seeming", level: 5 },
    { name: "Skill Empowerment", level: 5 },
    { name: "Steel Wind Strike", level: 5 },
    { name: "Summon Aberration", level: 5 },
    { name: "Summon Celestial Spirit", level: 5 },
    { name: "Summon Construct", level: 5 },
    { name: "Summon Elemental", level: 5 },
    { name: "Summon Fiend", level: 5 },
    { name: "Summon Greater Demon", level: 5 },
    { name: "Summon Shadowspawn", level: 5 },
    { name: "Summon Undead", level: 5 },
    { name: "Teleportation Circle", level: 5 },
    { name: "Wall of Force", level: 5 },
    { name: "Wall of Stone", level: 5 },
    { name: "Arcane Gate", level: 6 },
    { name: "Blade Barrier", level: 6 },
    { name: "Chain Lightning", level: 6 },
    { name: "Circle of Death", level: 6 },
    { name: "Conjure Fey", level: 6 },
    { name: "Conjure Woodland Beings", level: 6 },
    { name: "Create Undead", level: 6 },
    { name: "Disintegrate", level: 6 },
    { name: "Drawmij's Instant Summons", level: 6 },
    { name: "Find the Path", level: 6 },
    { name: "Forbiddance", level: 6 },
    { name: "Globe of Invulnerability", level: 6 },
    { name: "Guards and Wards", level: 6 },
    { name: "Heal", level: 6 },
    { name: "Magic Jar", level: 6 },
    { name: "Mass Suggestion", level: 6 },
    { name: "Move Earth", level: 6 },
    { name: "Planar Ally", level: 6 },
    { name: "Programmed Illusion", level: 6 },
    { name: "Raise Dead", level: 6 },
    { name: "Sunbeam", level: 6 },
    { name: "Symbol", level: 6 },
    { name: "Teleportation Circle", level: 6 },
    { name: "Transport via Plants", level: 6 },
    { name: "True Seeing", level: 6 },
    { name: "Wall of Ice", level: 6 },
    { name: "Word of Recall", level: 6 },
    { name: "Conjure Celestial", level: 7 },
    { name: "Conjure Elemental", level: 7 },
    { name: "Conjure Fey", level: 7 },
    { name: "Conjure Woodland Beings", level: 7 },
    { name: "Create Undead", level: 7 },
    { name: "Divine Word", level: 7 },
    { name: "Etherealness", level: 7 },
    { name: "Finger of Death", level: 7 },
    { name: "Fire Storm", level: 7 },
    { name: "Plane Shift", level: 7 },
    { name: "Prismatic Spray", level: 7 },
    { name: "Project Image", level: 7 },
    { name: "Regenerate", level: 7 },
    { name: "Resurrection", level: 7 },
    { name: "Reverse Gravity", level: 7 },
    { name: "Simulacrum", level: 7 },
    { name: "Teleport", level: 7 },
    { name: "Temple of the Gods", level: 7 },
    { name: "Wall of Force", level: 7 },
    { name: "Word of Recall", level: 7 },
    { name: "Animal Shapes", level: 8 },
    { name: "Antimagic Field", level: 8 },
    { name: "Clone", level: 8 },
    { name: "Control Weather", level: 8 },
    { name: "Create Undead", level: 8 },
    { name: "Earthquake", level: 8 },
    { name: "Holy Aura", level: 8 },
    { name: "Incendiary Cloud", level: 8 },
    { name: "Mind Blank", level: 8 },
    { name: "Planar Ally", level: 8 },
    { name: "Power Word Stun", level: 8 },
    { name: "Sunburst", level: 8 },
    { name: "Teleport", level: 8 },
    { name: "Tsunami", level: 8 },
    { name: "Wall of Ice", level: 8 },
    { name: "Astral Projection", level: 9 },
    { name: "Conjure Animals", level: 9 },
    { name: "Conjure Celestial", level: 9 },
    { name: "Conjure Elemental", level: 9 },
    { name: "Conjure Fey", level: 9 },
    { name: "Conjure Woodland Beings", level: 9 },
    { name: "Foresight", level: 9 },
    { name: "Gate", level: 9 },
    { name: "Mass Heal", level: 9 },
    { name: "Meteor Swarm", level: 9 },
    { name: "Power Word Kill", level: 9 },
    { name: "Prismatic Wall", level: 9 },
    { name: "Shapechange", level: 9 },
    { name: "Storm of Vengeance", level: 9 },
    { name: "Time Stop", level: 9 },
    { name: "True Polymorph", level: 9 },
    { name: "Wish", level: 9 }
  ],
  Enchantment: [
    { name: "Friends", level: 0 },
    { name: "Vicious Mockery", level: 0 },
    { name: "Animal Friendship", level: 1 },
    { name: "Bless", level: 1 },
    { name: "Charm Person", level: 1 },
    { name: "Command", level: 1 },
    { name: "Compelled Duel", level: 1 },
    { name: "Dissonant Whispers", level: 1 },
    { name: "Faerie Fire", level: 1 },
    { name: "Heroism", level: 1 },
    { name: "Sleep", level: 1 },
    { name: "Tasha's Hideous Laughter", level: 1 },
    { name: "Animal Messenger", level: 2 },
    { name: "Barkskin", level: 2 },
    { name: "Blindness/Deafness", level: 2 },
    { name: "Calm Emotions", level: 2 },
    { name: "Crown of Madness", level: 2 },
    { name: "Detect Thoughts", level: 2 },
    { name: "Enhance Ability", level: 2 },
    { name: "Enthrall", level: 2 },
    { name: "Find Steed", level: 2 },
    { name: "Gentle Repose", level: 2 },
    { name: "Hold Person", level: 2 },
    { name: "Invisibility", level: 2 },
    { name: "Knock", level: 2 },
    { name: "Lesser Restoration", level: 2 },
    { name: "Magic Weapon", level: 2 },
    { name: "Moonbeam", level: 2 },
    { name: "Nystul's Magic Aura", level: 2 },
    { name: "Pass without Trace", level: 2 },
    { name: "Protection from Poison", level: 2 },
    { name: "Ray of Enfeeblement", level: 2 },
    { name: "Rope Trick", level: 2 },
    { name: "See Invisibility", level: 2 },
    { name: "Spider Climb", level: 2 },
    { name: "Spike Growth", level: 2 },
    { name: "Suggestion", level: 2 },
    { name: "Zone of Truth", level: 2 },
    { name: "Animate Dead", level: 3 },
    { name: "Aura of Vitality", level: 3 },
    { name: "Beacon of Hope", level: 3 },
    { name: "Bestow Curse", level: 3 },
    { name: "Clairvoyance", level: 3 },
    { name: "Conjure Animals", level: 3 },
    { name: "Conjure Minor Elementals", level: 3 },
    { name: "Conjure Woodland Beings", level: 3 },
    { name: "Create Food and Water", level: 3 },
    { name: "Daylight", level: 3 },
    { name: "Dispel Magic", level: 3 },
    { name: "Elemental Weapon", level: 3 },
    { name: "Feign Death", level: 3 },
    { name: "Fireball", level: 3 },
    { name: "Flame Arrows", level: 3 },
    { name: "Fly", level: 3 },
    { name: "Gaseous Form", level: 3 },
    { name: "Glyph of Warding", level: 3 },
    { name: "Haste", level: 3 },
    { name: "Hypnotic Pattern", level: 3 },
    { name: "Leomund's Tiny Hut", level: 3 },
    { name: "Life Transference", level: 3 },
    { name: "Lightning Bolt", level: 3 },
    { name: "Magic Circle", level: 3 },
    { name: "Mass Healing Word", level: 3 },
    { name: "Melf's Minute Meteors", level: 3 },
    { name: "Phantom Steed", level: 3 },
    { name: "Plant Growth", level: 3 },
    { name: "Protection from Energy", level: 3 },
    { name: "Remove Curse", level: 3 },
    { name: "Revivify", level: 3 },
    { name: "Sending", level: 3 },
    { name: "Sleet Storm", level: 3 },
    { name: "Speak with Plants", level: 3 },
    { name: "Spirit Guardians", level: 3 },
    { name: "Stinking Cloud", level: 3 },
    { name: "Summon Aberration", level: 3 },
    { name: "Summon Celestial Spirit", level: 3 },
    { name: "Summon Construct", level: 3 },
    { name: "Summon Elemental", level: 3 },
    { name: "Summon Fiend", level: 3 },
    { name: "Summon Draconic Spirit", level: 3 },
    { name: "Summon Undead", level: 3 },
    { name: "Thunder Step", level: 3 },
    { name: "Tiny Servant", level: 3 },
    { name: "Tongues", level: 3 },
    { name: "Vampiric Touch", level: 3 },
    { name: "Wall of Water", level: 3 },
    { name: "Water Breathing", level: 3 },
    { name: "Water Walk", level: 3 },
    { name: "Wind Wall", level: 3 },
    { name: "Aura of Life", level: 4 },
    { name: "Banishment", level: 4 },
    { name: "Blight", level: 4 },
    { name: "Charm Monster", level: 4 },
    { name: "Compulsion", level: 4 },
    { name: "Conjure Elemental", level: 4 },
    { name: "Conjure Fey", level: 4 },
    { name: "Control Water", level: 4 },
    { name: "Death Ward", level: 4 },
    { name: "Dimension Door", level: 4 },
    { name: "Divination", level: 4 },
    { name: "Dominate Beast", level: 4 },
    { name: "Evard's Black Tentacles", level: 4 },
    { name: "Fabricate", level: 4 },
    { name: "Find Greater Steed", level: 4 },
    { name: "Fire Shield", level: 4 },
    { name: "Freedom of Movement", level: 4 },
    { name: "Giant Insect", level: 4 },
    { name: "Greater Invisibility", level: 4 },
    { name: "Guardian of Faith", level: 4 },
    { name: "Hallucinatory Terrain", level: 4 },
    { name: "Ice Storm", level: 4 },
    { name: "Leomund's Secret Chest", level: 4 },
    { name: "Locate Creature", level: 4 },
    { name: "Mordenkainen's Private Sanctum", level: 4 },
    { name: "Otiluke's Resilient Sphere", level: 4 },
    { name: "Polymorph", level: 4 },
    { name: "Private Sanctum", level: 4 },
    { name: "Rauryk's Telepathic Bond", level: 4 },
    { name: "Resilient Sphere", level: 4 },
    { name: "Secret Chest", level: 4 },
    { name: "Sickening Radiance", level: 4 },
    { name: "Stoneskin", level: 4 },
    { name: "Summon Greater Demon", level: 4 },
    { name: "Summon Shadow Spirit", level: 4 },
    { name: "Summon Undead Spirit", level: 4 },
    { name: "Teleportation Circle", level: 4 },
    { name: "Wall of Fire", level: 4 },
    { name: "Animate Objects", level: 5 },
    { name: "Antilife Shell", level: 5 },
    { name: "Awaken", level: 5 },
    { name: "Circle of Power", level: 5 },
    { name: "Cloudkill", level: 5 },
    { name: "Commune", level: 5 },
    { name: "Conjure Celestial", level: 5 },
    { name: "Conjure Elemental", level: 5 },
    { name: "Conjure Volley", level: 5 },
    { name: "Contact Other Plane", level: 5 },
    { name: "Control Winds", level: 5 },
    { name: "Creation", level: 5 },
    { name: "Dawn", level: 5 },
    { name: "Destructive Wave", level: 5 },
    { name: "Dispel Evil and Good", level: 5 },
    { name: "Dominate Person", level: 5 },
    { name: "Dream", level: 5 },
    { name: "Flame Strike", level: 5 },
    { name: "Geas", level: 5 },
    { name: "Greater Restoration", level: 5 },
    { name: "Hallow", level: 5 },
    { name: "Hold Monster", level: 5 },
    { name: "Holy Weapon", level: 5 },
    { name: "Insect Plague", level: 5 },
    { name: "Legend Lore", level: 5 },
    { name: "Mass Cure Wounds", level: 5 },
    { name: "Mass Healing Word", level: 5 },
    { name: "Misty Step", level: 5 },
    { name: "Modify Memory", level: 5 },
    { name: "Planar Binding", level: 5 },
    { name: "Raise Dead", level: 5 },
    { name: "Reincarnate", level: 5 },
    { name: "Rope Trick", level: 5 },
    { name: "Scrying", level: 5 },
    { name: "Seeming", level: 5 },
    { name: "Skill Empowerment", level: 5 },
    { name: "Steel Wind Strike", level: 5 },
    { name: "Summon Aberration", level: 5 },
    { name: "Summon Celestial Spirit", level: 5 },
    { name: "Summon Construct", level: 5 },
    { name: "Summon Elemental", level: 5 },
    { name: "Summon Fiend", level: 5 },
    { name: "Summon Greater Demon", level: 5 },
    { name: "Summon Shadowspawn", level: 5 },
    { name: "Summon Undead", level: 5 },
    { name: "Teleportation Circle", level: 5 },
    { name: "Wall of Force", level: 5 },
    { name: "Wall of Stone", level: 5 },
    { name: "Arcane Gate", level: 6 },
    { name: "Blade Barrier", level: 6 },
    { name: "Chain Lightning", level: 6 },
    { name: "Circle of Death", level: 6 },
    { name: "Conjure Fey", level: 6 },
    { name: "Conjure Woodland Beings", level: 6 },
    { name: "Create Undead", level: 6 },
    { name: "Disintegrate", level: 6 },
    { name: "Drawmij's Instant Summons", level: 6 },
    { name: "Find the Path", level: 6 },
    { name: "Forbiddance", level: 6 },
    { name: "Globe of Invulnerability", level: 6 },
    { name: "Guards and Wards", level: 6 },
    { name: "Heal", level: 6 },
    { name: "Magic Jar", level: 6 },
    { name: "Mass Suggestion", level: 6 },
    { name: "Move Earth", level: 6 },
    { name: "Planar Ally", level: 6 },
    { name: "Programmed Illusion", level: 6 },
    { name: "Raise Dead", level: 6 },
    { name: "Sunbeam", level: 6 },
    { name: "Symbol", level: 6 },
    { name: "Teleportation Circle", level: 6 },
    { name: "Transport via Plants", level: 6 },
    { name: "True Seeing", level: 6 },
    { name: "Wall of Ice", level: 6 },
    { name: "Word of Recall", level: 6 },
    { name: "Conjure Celestial", level: 7 },
    { name: "Conjure Elemental", level: 7 },
    { name: "Conjure Fey", level: 7 },
    { name: "Conjure Woodland Beings", level: 7 },
    { name: "Create Undead", level: 7 },
    { name: "Divine Word", level: 7 },
    { name: "Etherealness", level: 7 },
    { name: "Finger of Death", level: 7 },
    { name: "Fire Storm", level: 7 },
    { name: "Plane Shift", level: 7 },
    { name: "Prismatic Spray", level: 7 },
    { name: "Project Image", level: 7 },
    { name: "Regenerate", level: 7 },
    { name: "Resurrection", level: 7 },
    { name: "Reverse Gravity", level: 7 },
    { name: "Simulacrum", level: 7 },
    { name: "Teleport", level: 7 },
    { name: "Temple of the Gods", level: 7 },
    { name: "Wall of Force", level: 7 },
    { name: "Word of Recall", level: 7 },
    { name: "Animal Shapes", level: 8 },
    { name: "Antimagic Field", level: 8 },
    { name: "Clone", level: 8 },
    { name: "Control Weather", level: 8 },
    { name: "Create Undead", level: 8 },
    { name: "Dominate Monster", level: 8 },
    { name: "Earthquake", level: 8 },
    { name: "Holy Aura", level: 8 },
    { name: "Incendiary Cloud", level: 8 },
    { name: "Mind Blank", level: 8 },
    { name: "Planar Ally", level: 8 },
    { name: "Power Word Stun", level: 8 },
    { name: "Sunburst", level: 8 },
    { name: "Teleport", level: 8 },
    { name: "Tsunami", level: 8 },
    { name: "Wall of Ice", level: 8 },
    { name: "Astral Projection", level: 9 },
    { name: "Conjure Animals", level: 9 },
    { name: "Conjure Celestial", level: 9 },
    { name: "Conjure Elemental", level: 9 },
    { name: "Conjure Fey", level: 9 },
    { name: "Conjure Woodland Beings", level: 9 },
    { name: "Dominate Monster", level: 9 },
    { name: "Gate", level: 9 },
    { name: "Mass Heal", level: 9 },
    { name: "Meteor Swarm", level: 9 },
    { name: "Power Word Kill", level: 9 },
    { name: "Prismatic Wall", level: 9 },
    { name: "Shapechange", level: 9 },
    { name: "Storm of Vengeance", level: 9 },
    { name: "Time Stop", level: 9 },
    { name: "True Polymorph", level: 9 },
    { name: "Wish", level: 9 }
  ],
  Evocation: [
    { name: "Acid Splash", level: 0 },
    { name: "Booming Blade", level: 0 },
    { name: "Chill Touch", level: 0 },
    { name: "Create Bonfire", level: 0 },
    { name: "Dancing Lights", level: 0 },
    { name: "Fire Bolt", level: 0 },
    { name: "Frostbite", level: 0 },
    { name: "Green-Flame Blade", level: 0 },
    { name: "Light", level: 0 },
    { name: "Lightning Lure", level: 0 },
    { name: "Magic Stone", level: 0 },
    { name: "Produce Flame", level: 0 },
    { name: "Ray of Frost", level: 0 },
    { name: "Sacred Flame", level: 0 },
    { name: "Shocking Grasp", level: 0 },
    { name: "Sword Burst", level: 0 },
    { name: "Thunderclap", level: 0 },
    { name: "Burning Hands", level: 1 },
    { name: "Cause Fear", level: 1 },
    { name: "Color Spray", level: 1 },
    { name: "Create or Destroy Water", level: 1 },
    { name: "Cure Wounds", level: 1 },
    { name: "Detect Poison and Disease", level: 1 },
    { name: "Guiding Bolt", level: 1 },
    { name: "Healing Word", level: 1 },
    { name: "Ice Knife", level: 1 },
    { name: "Inflict Wounds", level: 1 },
    { name: "Magic Missile", level: 1 },
    { name: "Purify Food and Drink", level: 1 },
    { name: "Searing Smite", level: 1 },
    { name: "Shield of Faith", level: 1 },
    { name: "Shillelagh", level: 1 },
    { name: "Speak with Animals", level: 1 },
    { name: "Thunderwave", level: 1 },
    { name: "Wrathful Smite", level: 1 },
    { name: "Acid Arrow", level: 2 },
    { name: "Aganazzar's Scorcher", level: 2 },
    { name: "Blindness/Deafness", level: 2 },
    { name: "Cloud of Daggers", level: 2 },
    { name: "Continual Flame", level: 2 },
    { name: "Crown of Madness", level: 2 },
    { name: "Darkness", level: 2 },
    { name: "Darkvision", level: 2 },
    { name: "Dust of Disappearance", level: 2 },
    { name: "Earthbind", level: 2 },
    { name: "Enlarge/Reduce", level: 2 },
    { name: "Flaming Sphere", level: 2 },
    { name: "Gust of Wind", level: 2 },
    { name: "Healing Spirit", level: 2 },
    { name: "Hold Person", level: 2 },
    { name: "Invisibility", level: 2 },
    { name: "Knock", level: 2 },
    { name: "Lesser Restoration", level: 2 },
    { name: "Locate Animals or Plants", level: 2 },
    { name: "Locate Object", level: 2 },
    { name: "Magic Weapon", level: 2 },
    { name: "Maximilian's Earthen Grasp", level: 2 },
    { name: "Moonbeam", level: 2 },
    { name: "Pass without Trace", level: 2 },
    { name: "Prayer of Healing", level: 2 },
    { name: "Protection from Poison", level: 2 },
    { name: "Ray of Enfeeblement", level: 2 },
    { name: "Rope Trick", level: 2 },
    { name: "Scorching Ray", level: 2 },
    { name: "See Invisibility", level: 2 },
    { name: "Shatter", level: 2 },
    { name: "Spider Climb", level: 2 },
    { name: "Spike Growth", level: 2 },
    { name: "Spiritual Weapon", level: 2 },
    { name: "Summon Beast", level: 2 },
    { name: "Summon Fey Spirit", level: 2 },
    { name: "Summon Shadowspawn", level: 2 },
    { name: "Summon Undead", level: 2 },
    { name: "Web", level: 2 },
    { name: "Zone of Truth", level: 2 },
    { name: "Animate Dead", level: 3 },
    { name: "Aura of Vitality", level: 3 },
    { name: "Beacon of Hope", level: 3 },
    { name: "Bestow Curse", level: 3 },
    { name: "Call Lightning", level: 3 },
    { name: "Clairvoyance", level: 3 },
    { name: "Conjure Animals", level: 3 },
    { name: "Conjure Minor Elementals", level: 3 },
    { name: "Conjure Woodland Beings", level: 3 },
    { name: "Create Food and Water", level: 3 },
    { name: "Daylight", level: 3 },
    { name: "Dispel Magic", level: 3 },
    { name: "Elemental Weapon", level: 3 },
    { name: "Feign Death", level: 3 },
    { name: "Fireball", level: 3 },
    { name: "Flame Arrows", level: 3 },
    { name: "Fly", level: 3 },
    { name: "Gaseous Form", level: 3 },
    { name: "Glyph of Warding", level: 3 },
    { name: "Haste", level: 3 },
    { name: "Hypnotic Pattern", level: 3 },
    { name: "Leomund's Tiny Hut", level: 3 },
    { name: "Life Transference", level: 3 },
    { name: "Lightning Bolt", level: 3 },
    { name: "Magic Circle", level: 3 },
    { name: "Mass Healing Word", level: 3 },
    { name: "Melf's Minute Meteors", level: 3 },
    { name: "Phantom Steed", level: 3 },
    { name: "Plant Growth", level: 3 },
    { name: "Protection from Energy", level: 3 },
    { name: "Remove Curse", level: 3 },
    { name: "Revivify", level: 3 },
    { name: "Sending", level: 3 },
    { name: "Sleet Storm", level: 3 },
    { name: "Speak with Plants", level: 3 },
    { name: "Spirit Guardians", level: 3 },
    { name: "Stinking Cloud", level: 3 },
    { name: "Summon Aberration", level: 3 },
    { name: "Summon Celestial Spirit", level: 3 },
    { name: "Summon Construct", level: 3 },
    { name: "Summon Elemental", level: 3 },
    { name: "Summon Fiend", level: 3 },
    { name: "Summon Draconic Spirit", level: 3 },
    { name: "Summon Undead", level: 3 },
    { name: "Thunder Step", level: 3 },
    { name: "Tiny Servant", level: 3 },
    { name: "Tongues", level: 3 },
    { name: "Vampiric Touch", level: 3 },
    { name: "Wall of Water", level: 3 },
    { name: "Water Breathing", level: 3 },
    { name: "Water Walk", level: 3 },
    { name: "Wind Wall", level: 3 },
    { name: "Aura of Life", level: 4 },
    { name: "Banishment", level: 4 },
    { name: "Blight", level: 4 },
    { name: "Charm Monster", level: 4 },
    { name: "Compulsion", level: 4 },
    { name: "Conjure Elemental", level: 4 },
    { name: "Conjure Fey", level: 4 },
    { name: "Control Water", level: 4 },
    { name: "Death Ward", level: 4 },
    { name: "Dimension Door", level: 4 },
    { name: "Divination", level: 4 },
    { name: "Dominate Beast", level: 4 },
    { name: "Evard's Black Tentacles", level: 4 },
    { name: "Fabricate", level: 4 },
    { name: "Find Greater Steed", level: 4 },
    { name: "Fire Shield", level: 4 },
    { name: "Freedom of Movement", level: 4 },
    { name: "Giant Insect", level: 4 },
    { name: "Greater Invisibility", level: 4 },
    { name: "Guardian of Faith", level: 4 },
    { name: "Hallucinatory Terrain", level: 4 },
    { name: "Ice Storm", level: 4 },
    { name: "Leomund's Secret Chest", level: 4 },
    { name: "Locate Creature", level: 4 },
    { name: "Mordenkainen's Private Sanctum", level: 4 },
    { name: "Otiluke's Resilient Sphere", level: 4 },
    { name: "Polymorph", level: 4 },
    { name: "Private Sanctum", level: 4 },
    { name: "Rauryk's Telepathic Bond", level: 4 },
    { name: "Resilient Sphere", level: 4 },
    { name: "Secret Chest", level: 4 },
    { name: "Sickening Radiance", level: 4 },
    { name: "Stoneskin", level: 4 },
    { name: "Summon Greater Demon", level: 4 },
    { name: "Summon Shadow Spirit", level: 4 },
    { name: "Summon Undead Spirit", level: 4 },
    { name: "Teleportation Circle", level: 4 },
    { name: "Wall of Fire", level: 4 },
    { name: "Animate Objects", level: 5 },
    { name: "Antilife Shell", level: 5 },
    { name: "Awaken", level: 5 },
    { name: "Circle of Power", level: 5 },
    { name: "Cloudkill", level: 5 },
    { name: "Commune", level: 5 },
    { name: "Cone of Cold", level: 5 },
    { name: "Conjure Celestial", level: 5 },
    { name: "Conjure Elemental", level: 5 },
    { name: "Conjure Volley", level: 5 },
    { name: "Contact Other Plane", level: 5 },
    { name: "Control Winds", level: 5 },
    { name: "Creation", level: 5 },
    { name: "Dawn", level: 5 },
    { name: "Destructive Wave", level: 5 },
    { name: "Dispel Evil and Good", level: 5 },
    { name: "Dominate Person", level: 5 },
    { name: "Dream", level: 5 },
    { name: "Flame Strike", level: 5 },
    { name: "Geas", level: 5 },
    { name: "Greater Restoration", level: 5 },
    { name: "Hallow", level: 5 },
    { name: "Hold Monster", level: 5 },
    { name: "Holy Weapon", level: 5 },
    { name: "Insect Plague", level: 5 },
    { name: "Legend Lore", level: 5 },
    { name: "Mass Cure Wounds", level: 5 },
    { name: "Mass Healing Word", level: 5 },
    { name: "Misty Step", level: 5 },
    { name: "Modify Memory", level: 5 },
    { name: "Planar Binding", level: 5 },
    { name: "Raise Dead", level: 5 },
    { name: "Reincarnate", level: 5 },
    { name: "Rope Trick", level: 5 },
    { name: "Scrying", level: 5 },
    { name: "Seeming", level: 5 },
    { name: "Skill Empowerment", level: 5 },
    { name: "Steel Wind Strike", level: 5 },
    { name: "Summon Aberration", level: 5 },
    { name: "Summon Celestial Spirit", level: 5 },
    { name: "Summon Construct", level: 5 },
    { name: "Summon Elemental", level: 5 },
    { name: "Summon Fiend", level: 5 },
    { name: "Summon Greater Demon", level: 5 },
    { name: "Summon Shadowspawn", level: 5 },
    { name: "Summon Undead", level: 5 },
    { name: "Teleportation Circle", level: 5 },
    { name: "Wall of Force", level: 5 },
    { name: "Wall of Stone", level: 5 },
    { name: "Arcane Gate", level: 6 },
    { name: "Blade Barrier", level: 6 },
    { name: "Chain Lightning", level: 6 },
    { name: "Circle of Death", level: 6 },
    { name: "Conjure Fey", level: 6 },
    { name: "Conjure Woodland Beings", level: 6 },
    { name: "Create Undead", level: 6 },
    { name: "Disintegrate", level: 6 },
    { name: "Drawmij's Instant Summons", level: 6 },
    { name: "Find the Path", level: 6 },
    { name: "Forbiddance", level: 6 },
    { name: "Globe of Invulnerability", level: 6 },
    { name: "Guards and Wards", level: 6 },
    { name: "Heal", level: 6 },
    { name: "Magic Jar", level: 6 },
    { name: "Mass Suggestion", level: 6 },
    { name: "Move Earth", level: 6 },
    { name: "Planar Ally", level: 6 },
    { name: "Programmed Illusion", level: 6 },
    { name: "Raise Dead", level: 6 },
    { name: "Sunbeam", level: 6 },
    { name: "Symbol", level: 6 },
    { name: "Teleportation Circle", level: 6 },
    { name: "Transport via Plants", level: 6 },
    { name: "True Seeing", level: 6 },
    { name: "Wall of Ice", level: 6 },
    { name: "Word of Recall", level: 6 },
    { name: "Conjure Celestial", level: 7 },
    { name: "Conjure Elemental", level: 7 },
    { name: "Conjure Fey", level: 7 },
    { name: "Conjure Woodland Beings", level: 7 },
    { name: "Create Undead", level: 7 },
    { name: "Divine Word", level: 7 },
    { name: "Etherealness", level: 7 },
    { name: "Finger of Death", level: 7 },
    { name: "Fire Storm", level: 7 },
    { name: "Plane Shift", level: 7 },
    { name: "Prismatic Spray", level: 7 },
    { name: "Project Image", level: 7 },
    { name: "Regenerate", level: 7 },
    { name: "Resurrection", level: 7 },
    { name: "Reverse Gravity", level: 7 },
    { name: "Simulacrum", level: 7 },
    { name: "Teleport", level: 7 },
    { name: "Temple of the Gods", level: 7 },
    { name: "Wall of Force", level: 7 },
    { name: "Word of Recall", level: 7 },
    { name: "Animal Shapes", level: 8 },
    { name: "Antimagic Field", level: 8 },
    { name: "Clone", level: 8 },
    { name: "Control Weather", level: 8 },
    { name: "Create Undead", level: 8 },
    { name: "Earthquake", level: 8 },
    { name: "Holy Aura", level: 8 },
    { name: "Incendiary Cloud", level: 8 },
    { name: "Mind Blank", level: 8 },
    { name: "Planar Ally", level: 8 },
    { name: "Power Word Stun", level: 8 },
    { name: "Sunburst", level: 8 },
    { name: "Teleport", level: 8 },
    { name: "Tsunami", level: 8 },
    { name: "Wall of Ice", level: 8 },
    { name: "Astral Projection", level: 9 },
    { name: "Conjure Animals", level: 9 },
    { name: "Conjure Celestial", level: 9 },
    { name: "Conjure Elemental", level: 9 },
    { name: "Conjure Fey", level: 9 },
    { name: "Conjure Woodland Beings", level: 9 },
    { name: "Gate", level: 9 },
    { name: "Mass Heal", level: 9 },
    { name: "Meteor Swarm", level: 9 },
    { name: "Power Word Kill", level: 9 },
    { name: "Prismatic Wall", level: 9 },
    { name: "Shapechange", level: 9 },
    { name: "Storm of Vengeance", level: 9 },
    { name: "Time Stop", level: 9 },
    { name: "True Polymorph", level: 9 },
    { name: "Wish", level: 9 }
  ],
  Illusion: [
    { name: "Minor Illusion", level: 0 },
    { name: "Disguise Self", level: 1 },
    { name: "Illusory Script", level: 1 },
    { name: "Silent Image", level: 1 },
    { name: "Blur", level: 2 },
    { name: "Darkness", level: 2 },
    { name: "Dust of Disappearance", level: 2 },
    { name: "Invisibility", level: 2 },
    { name: "Magic Weapon", level: 2 },
    { name: "Mirror Image", level: 2 },
    { name: "Nystul's Magic Aura", level: 2 },
    { name: "Pass without Trace", level: 2 },
    { name: "Phantasmal Force", level: 2 },
    { name: "Rope Trick", level: 2 },
    { name: "Seeming", level: 2 },
    { name: "Spider Climb", level: 2 },
    { name: "Spike Growth", level: 2 },
    { name: "Suggestion", level: 2 },
    { name: "Zone of Truth", level: 2 },
    { name: "Animate Dead", level: 3 },
    { name: "Aura of Vitality", level: 3 },
    { name: "Beacon of Hope", level: 3 },
    { name: "Bestow Curse", level: 3 },
    { name: "Clairvoyance", level: 3 },
    { name: "Conjure Animals", level: 3 },
    { name: "Conjure Minor Elementals", level: 3 },
    { name: "Conjure Woodland Beings", level: 3 },
    { name: "Create Food and Water", level: 3 },
    { name: "Daylight", level: 3 },
    { name: "Dispel Magic", level: 3 },
    { name: "Elemental Weapon", level: 3 },
    { name: "Feign Death", level: 3 },
    { name: "Fireball", level: 3 },
    { name: "Flame Arrows", level: 3 },
    { name: "Fly", level: 3 },
    { name: "Gaseous Form", level: 3 },
    { name: "Glyph of Warding", level: 3 },
    { name: "Haste", level: 3 },
    { name: "Hypnotic Pattern", level: 3 },
    { name: "Leomund's Tiny Hut", level: 3 },
    { name: "Life Transference", level: 3 },
    { name: "Lightning Bolt", level: 3 },
    { name: "Magic Circle", level: 3 },
    { name: "Major Image", level: 3 },
    { name: "Mass Healing Word", level: 3 },
    { name: "Melf's Minute Meteors", level: 3 },
    { name: "Phantom Steed", level: 3 },
    { name: "Plant Growth", level: 3 },
    { name: "Protection from Energy", level: 3 },
    { name: "Remove Curse", level: 3 },
    { name: "Revivify", level: 3 },
    { name: "Sending", level: 3 },
    { name: "Sleet Storm", level: 3 },
    { name: "Speak with Plants", level: 3 },
    { name: "Spirit Guardians", level: 3 },
    { name: "Stinking Cloud", level: 3 },
    { name: "Summon Aberration", level: 3 },
    { name: "Summon Celestial Spirit", level: 3 },
    { name: "Summon Construct", level: 3 },
    { name: "Summon Elemental", level: 3 },
    { name: "Summon Fiend", level: 3 },
    { name: "Summon Draconic Spirit", level: 3 },
    { name: "Summon Undead", level: 3 },
    { name: "Thunder Step", level: 3 },
    { name: "Tiny Servant", level: 3 },
    { name: "Tongues", level: 3 },
    { name: "Vampiric Touch", level: 3 },
    { name: "Wall of Water", level: 3 },
    { name: "Water Breathing", level: 3 },
    { name: "Water Walk", level: 3 },
    { name: "Wind Wall", level: 3 },
    { name: "Aura of Life", level: 4 },
    { name: "Banishment", level: 4 },
    { name: "Blight", level: 4 },
    { name: "Charm Monster", level: 4 },
    { name: "Compulsion", level: 4 },
    { name: "Conjure Elemental", level: 4 },
    { name: "Conjure Fey", level: 4 },
    { name: "Control Water", level: 4 },
    { name: "Death Ward", level: 4 },
    { name: "Dimension Door", level: 4 },
    { name: "Divination", level: 4 },
    { name: "Dominate Beast", level: 4 },
    { name: "Evard's Black Tentacles", level: 4 },
    { name: "Fabricate", level: 4 },
    { name: "Find Greater Steed", level: 4 },
    { name: "Fire Shield", level: 4 },
    { name: "Freedom of Movement", level: 4 },
    { name: "Giant Insect", level: 4 },
    { name: "Greater Invisibility", level: 4 },
    { name: "Guardian of Faith", level: 4 },
    { name: "Hallucinatory Terrain", level: 4 },
    { name: "Ice Storm", level: 4 },
    { name: "Leomund's Secret Chest", level: 4 },
    { name: "Locate Creature", level: 4 },
    { name: "Mordenkainen's Private Sanctum", level: 4 },
    { name: "Otiluke's Resilient Sphere", level: 4 },
    { name: "Phantasmal Killer", level: 4 },
    { name: "Polymorph", level: 4 },
    { name: "Private Sanctum", level: 4 },
    { name: "Rauryk's Telepathic Bond", level: 4 },
    { name: "Resilient Sphere", level: 4 },
    { name: "Secret Chest", level: 4 },
    { name: "Sickening Radiance", level: 4 },
    { name: "Stoneskin", level: 4 },
    { name: "Summon Greater Demon", level: 4 },
    { name: "Summon Shadow Spirit", level: 4 },
    { name: "Summon Undead Spirit", level: 4 },
    { name: "Teleportation Circle", level: 4 },
    { name: "Wall of Fire", level: 4 },
    { name: "Animate Objects", level: 5 },
    { name: "Antilife Shell", level: 5 },
    { name: "Awaken", level: 5 },
    { name: "Circle of Power", level: 5 },
    { name: "Cloudkill", level: 5 },
    { name: "Commune", level: 5 },
    { name: "Conjure Celestial", level: 5 },
    { name: "Conjure Elemental", level: 5 },
    { name: "Conjure Volley", level: 5 },
    { name: "Contact Other Plane", level: 5 },
    { name: "Control Winds", level: 5 },
    { name: "Creation", level: 5 },
    { name: "Dawn", level: 5 },
    { name: "Destructive Wave", level: 5 },
    { name: "Dispel Evil and Good", level: 5 },
    { name: "Dominate Person", level: 5 },
    { name: "Dream", level: 5 },
    { name: "Flame Strike", level: 5 },
    { name: "Geas", level: 5 },
    { name: "Greater Restoration", level: 5 },
    { name: "Hallow", level: 5 },
    { name: "Hold Monster", level: 5 },
    { name: "Holy Weapon", level: 5 },
    { name: "Insect Plague", level: 5 },
    { name: "Legend Lore", level: 5 },
    { name: "Mass Cure Wounds", level: 5 },
    { name: "Mass Healing Word", level: 5 },
    { name: "Misty Step", level: 5 },
    { name: "Modify Memory", level: 5 },
    { name: "Planar Binding", level: 5 },
    { name: "Raise Dead", level: 5 },
    { name: "Reincarnate", level: 5 },
    { name: "Rope Trick", level: 5 },
    { name: "Scrying", level: 5 },
    { name: "Seeming", level: 5 },
    { name: "Skill Empowerment", level: 5 },
    { name: "Steel Wind Strike", level: 5 },
    { name: "Summon Aberration", level: 5 },
    { name: "Summon Celestial Spirit", level: 5 },
    { name: "Summon Construct", level: 5 },
    { name: "Summon Elemental", level: 5 },
    { name: "Summon Fiend", level: 5 },
    { name: "Summon Greater Demon", level: 5 },
    { name: "Summon Shadowspawn", level: 5 },
    { name: "Summon Undead", level: 5 },
    { name: "Teleportation Circle", level: 5 },
    { name: "Wall of Force", level: 5 },
    { name: "Wall of Stone", level: 5 },
    { name: "Arcane Gate", level: 6 },
    { name: "Blade Barrier", level: 6 },
    { name: "Chain Lightning", level: 6 },
    { name: "Circle of Death", level: 6 },
    { name: "Conjure Fey", level: 6 },
    { name: "Conjure Woodland Beings", level: 6 },
    { name: "Create Undead", level: 6 },
    { name: "Disintegrate", level: 6 },
    { name: "Drawmij's Instant Summons", level: 6 },
    { name: "Find the Path", level: 6 },
    { name: "Forbiddance", level: 6 },
    { name: "Globe of Invulnerability", level: 6 },
    { name: "Guards and Wards", level: 6 },
    { name: "Heal", level: 6 },
    { name: "Magic Jar", level: 6 },
    { name: "Mass Suggestion", level: 6 },
    { name: "Move Earth", level: 6 },
    { name: "Planar Ally", level: 6 },
    { name: "Programmed Illusion", level: 6 },
    { name: "Raise Dead", level: 6 },
    { name: "Sunbeam", level: 6 },
    { name: "Symbol", level: 6 },
    { name: "Teleportation Circle", level: 6 },
    { name: "Transport via Plants", level: 6 },
    { name: "True Seeing", level: 6 },
    { name: "Wall of Ice", level: 6 },
    { name: "Word of Recall", level: 6 },
    { name: "Conjure Celestial", level: 7 },
    { name: "Conjure Elemental", level: 7 },
    { name: "Conjure Fey", level: 7 },
    { name: "Conjure Woodland Beings", level: 7 },
    { name: "Create Undead", level: 7 },
    { name: "Divine Word", level: 7 },
    { name: "Etherealness", level: 7 },
    { name: "Finger of Death", level: 7 },
    { name: "Fire Storm", level: 7 },
    { name: "Mirage Arcane", level: 7 },
    { name: "Plane Shift", level: 7 },
    { name: "Prismatic Spray", level: 7 },
    { name: "Project Image", level: 7 },
    { name: "Regenerate", level: 7 },
    { name: "Resurrection", level: 7 },
    { name: "Reverse Gravity", level: 7 },
    { name: "Simulacrum", level: 7 },
    { name: "Teleport", level: 7 },
    { name: "Temple of the Gods", level: 7 },
    { name: "Wall of Force", level: 7 },
    { name: "Word of Recall", level: 7 },
    { name: "Animal Shapes", level: 8 },
    { name: "Antimagic Field", level: 8 },
    { name: "Clone", level: 8 },
    { name: "Control Weather", level: 8 },
    { name: "Create Undead", level: 8 },
    { name: "Earthquake", level: 8 },
    { name: "Holy Aura", level: 8 },
    { name: "Incendiary Cloud", level: 8 },
    { name: "Illusory Dragon", level: 8 },
    { name: "Mind Blank", level: 8 },
    { name: "Planar Ally", level: 8 },
    { name: "Power Word Stun", level: 8 },
    { name: "Sunburst", level: 8 },
    { name: "Teleport", level: 8 },
    { name: "Tsunami", level: 8 },
    { name: "Wall of Ice", level: 8 },
    { name: "Astral Projection", level: 9 },
    { name: "Conjure Animals", level: 9 },
    { name: "Conjure Celestial", level: 9 },
    { name: "Conjure Elemental", level: 9 },
    { name: "Conjure Fey", level: 9 },
    { name: "Conjure Woodland Beings", level: 9 },
    { name: "Gate", level: 9 },
    { name: "Mass Heal", level: 9 },
    { name: "Meteor Swarm", level: 9 },
    { name: "Power Word Kill", level: 9 },
    { name: "Prismatic Wall", level: 9 },
    { name: "Shapechange", level: 9 },
    { name: "Storm of Vengeance", level: 9 },
    { name: "Time Stop", level: 9 },
    { name: "True Polymorph", level: 9 },
    { name: "Weird", level: 9 },
    { name: "Wish", level: 9 }
  ],
  Necromancy: [
    { name: "Chill Touch", level: 0 },
    { name: "Toll the Dead", level: 0 },
    { name: "Cause Fear", level: 1 },
    { name: "False Life", level: 1 },
    { name: "Inflict Wounds", level: 1 },
    { name: "Ray of Sickness", level: 1 },
    { name: "Blindness/Deafness", level: 2 },
    { name: "Gentle Repose", level: 2 },
    { name: "Ray of Enfeeblement", level: 2 },
    { name: "Animate Dead", level: 3 },
    { name: "Bestow Curse", level: 3 },
    { name: "Feign Death", level: 3 },
    { name: "Life Transference", level: 3 },
    { name: "Revivify", level: 3 },
    { name: "Speak with Dead", level: 3 },
    { name: "Summon Undead", level: 3 },
    { name: "Vampiric Touch", level: 3 },
    { name: "Blight", level: 4 },
    { name: "Death Ward", level: 4 },
    { name: "Dominate Beast", level: 4 },
    { name: "Summon Undead Spirit", level: 4 },
    { name: "Cloudkill", level: 5 },
    { name: "Contagion", level: 5 },
    { name: "Danse Macabre", level: 5 },
    { name: "Destructive Wave", level: 5 },
    { name: "Dominate Person", level: 5 },
    { name: "Geas", level: 5 },
    { name: "Hallow", level: 5 },
    { name: "Hold Monster", level: 5 },
    { name: "Insect Plague", level: 5 },
    { name: "Mass Cure Wounds", level: 5 },
    { name: "Modify Memory", level: 5 },
    { name: "Raise Dead", level: 5 },
    { name: "Reincarnate", level: 5 },
    { name: "Summon Undead", level: 5 },
    { name: "Circle of Death", level: 6 },
    { name: "Create Undead", level: 6 },
    { name: "Eyebite", level: 6 },
    { name: "Harm", level: 6 },
    { name: "Magic Jar", level: 6 },
    { name: "Mass Suggestion", level: 6 },
    { name: "Raise Dead", level: 6 },
    { name: "Create Undead", level: 7 },
    { name: "Finger of Death", level: 7 },
    { name: "Plane Shift", level: 7 },
    { name: "Resurrection", level: 7 },
    { name: "Symbol", level: 7 },
    { name: "Clone", level: 8 },
    { name: "Create Undead", level: 8 },
    { name: "Demiplane", level: 8 },
    { name: "Dominate Monster", level: 8 },
    { name: "Holy Aura", level: 8 },
    { name: "Power Word Stun", level: 8 },
    { name: "Astral Projection", level: 9 },
    { name: "Clone", level: 9 },
    { name: "Imprisonment", level: 9 },
    { name: "Mass Heal", level: 9 },
    { name: "Power Word Kill", level: 9 },
    { name: "Shapechange", level: 9 },
    { name: "True Polymorph", level: 9 },
    { name: "Wish", level: 9 }
  ],
  Transmutation: [
    { name: "Druidcraft", level: 0 },
    { name: "Gust", level: 0 },
    { name: "Infestation", level: 0 },
    { name: "Mending", level: 0 },
    { name: "Mold Earth", level: 0 },
    { name: "Move Earth", level: 0 },
    { name: "Shape Water", level: 0 },
    { name: "Thorn Whip", level: 0 },
    { name: "Animal Friendship", level: 1 },
    { name: "Armor of Agathys", level: 1 },
    { name: "Beast Bond", level: 1 },
    { name: "Bless", level: 1 },
    { name: "Burning Hands", level: 1 },
    { name: "Catapult", level: 1 },
    { name: "Ceremony", level: 1 },
    { name: "Charm Person", level: 1 },
    { name: "Color Spray", level: 1 },
    { name: "Command", level: 1 },
    { name: "Comprehend Languages", level: 1 },
    { name: "Create or Destroy Water", level: 1 },
    { name: "Cure Wounds", level: 1 },
    { name: "Detect Magic", level: 1 },
    { name: "Detect Poison and Disease", level: 1 },
    { name: "Disguise Self", level: 1 },
    { name: "Dissonant Whispers", level: 1 },
    { name: "Ensnaring Strike", level: 1 },
    { name: "Entangle", level: 1 },
    { name: "Expeditious Retreat", level: 1 },
    { name: "Faerie Fire", level: 1 },
    { name: "False Life", level: 1 },
    { name: "Find Familiar", level: 1 },
    { name: "Fog Cloud", level: 1 },
    { name: "Goodberry", level: 1 },
    { name: "Grease", level: 1 },
    { name: "Guiding Bolt", level: 1 },
    { name: "Healing Word", level: 1 },
    { name: "Heroism", level: 1 },
    { name: "Hex", level: 1 },
    { name: "Hunter's Mark", level: 1 },
    { name: "Identify", level: 1 },
    { name: "Ice Knife", level: 1 },
    { name: "Illusory Script", level: 1 },
    { name: "Inflict Wounds", level: 1 },
    { name: "Jump", level: 1 },
    { name: "Longstrider", level: 1 },
    { name: "Mage Armor", level: 1 },
    { name: "Magic Missile", level: 1 },
    { name: "Protection from Evil and Good", level: 1 },
    { name: "Protection from Poison", level: 1 },
    { name: "Purify Food and Drink", level: 1 },
    { name: "Ray of Sickness", level: 1 },
    { name: "Sanctuary", level: 1 },
    { name: "Searing Smite", level: 1 },
    { name: "Shield of Faith", level: 1 },
    { name: "Shillelagh", level: 1 },
    { name: "Silent Image", level: 1 },
    { name: "Sleep", level: 1 },
    { name: "Speak with Animals", level: 1 },
    { name: "Tasha's Hideous Laughter", level: 1 },
    { name: "Tenser's Floating Disk", level: 1 },
    { name: "Thunderwave", level: 1 },
    { name: "Unseen Servant", level: 1 },
    { name: "Wrathful Smite", level: 1 },
    { name: "Alter Self", level: 2 },
    { name: "Aid", level: 2 },
    { name: "Animal Messenger", level: 2 },
    { name: "Arcane Lock", level: 2 },
    { name: "Aura of Warding", level: 2 },
    { name: "Barkskin", level: 2 },
    { name: "Blindness/Deafness", level: 2 },
    { name: "Blur", level: 2 },
    { name: "Calm Emotions", level: 2 },
    { name: "Cloud of Daggers", level: 2 },
    { name: "Continual Flame", level: 2 },
    { name: "Crown of Madness", level: 2 },
    { name: "Darkness", level: 2 },
    { name: "Darkvision", level: 2 },
    { name: "Detect Thoughts", level: 2 },
    { name: "Dragon's Breath", level: 2 },
    { name: "Dust of Disappearance", level: 2 },
    { name: "Earthbind", level: 2 },
    { name: "Enhance Ability", level: 2 },
    { name: "Enlarge/Reduce", level: 2 },
    { name: "Enthrall", level: 2 },
    { name: "Find Steed", level: 2 },
    { name: "Flaming Sphere", level: 2 },
    { name: "Gentle Repose", level: 2 },
    { name: "Gust of Wind", level: 2 },
    { name: "Healing Spirit", level: 2 },
    { name: "Hold Person", level: 2 },
    { name: "Invisibility", level: 2 },
    { name: "Knock", level: 2 },
    { name: "Lesser Restoration", level: 2 },
    { name: "Levitate", level: 2 },
    { name: "Locate Animals or Plants", level: 2 },
    { name: "Locate Object", level: 2 },
    { name: "Magic Weapon", level: 2 },
    { name: "Maximilian's Earthen Grasp", level: 2 },
    { name: "Misty Step", level: 2 },
    { name: "Moonbeam", level: 2 },
    { name: "Nystul's Magic Aura", level: 2 },
    { name: "Pass without Trace", level: 2 },
    { name: "Prayer of Healing", level: 2 },
    { name: "Protection from Energy", level: 2 },
    { name: "Protection from Poison", level: 2 },
    { name: "Ray of Enfeeblement", level: 2 },
    { name: "Rope Trick", level: 2 },
    { name: "Scorching Ray", level: 2 },
    { name: "See Invisibility", level: 2 },
    { name: "Shatter", level: 2 },
    { name: "Spider Climb", level: 2 },
    { name: "Spike Growth", level: 2 },
    { name: "Spiritual Weapon", level: 2 },
    { name: "Suggestion", level: 2 },
    { name: "Summon Beast", level: 2 },
    { name: "Summon Fey Spirit", level: 2 },
    { name: "Summon Shadowspawn", level: 2 },
    { name: "Summon Undead", level: 2 },
    { name: "Web", level: 2 },
    { name: "Zone of Truth", level: 2 },
    { name: "Animate Dead", level: 3 },
    { name: "Aura of Vitality", level: 3 },
    { name: "Beacon of Hope", level: 3 },
    { name: "Bestow Curse", level: 3 },
    { name: "Call Lightning", level: 3 },
    { name: "Clairvoyance", level: 3 },
    { name: "Conjure Animals", level: 3 },
    { name: "Conjure Minor Elementals", level: 3 },
    { name: "Conjure Woodland Beings", level: 3 },
    { name: "Create Food and Water", level: 3 },
    { name: "Daylight", level: 3 },
    { name: "Dispel Magic", level: 3 },
    { name: "Elemental Weapon", level: 3 },
    { name: "Enemies Abound", level: 3 },
    { name: "Erupting Earth", level: 3 },
    { name: "Feign Death", level: 3 },
    { name: "Fireball", level: 3 },
    { name: "Flame Arrows", level: 3 },
    { name: "Fly", level: 3 },
    { name: "Gaseous Form", level: 3 },
    { name: "Glyph of Warding", level: 3 },
    { name: "Haste", level: 3 },
    { name: "Hypnotic Pattern", level: 3 },
    { name: "Leomund's Tiny Hut", level: 3 },
    { name: "Life Transference", level: 3 },
    { name: "Lightning Bolt", level: 3 },
    { name: "Magic Circle", level: 3 },
    { name: "Mass Healing Word", level: 3 },
    { name: "Melf's Minute Meteors", level: 3 },
    { name: "Nondetection", level: 3 },
    { name: "Phantom Steed", level: 3 },
    { name: "Plant Growth", level: 3 },
    { name: "Protection from Energy", level: 3 },
    { name: "Remove Curse", level: 3 },
    { name: "Revivify", level: 3 },
    { name: "Sending", level: 3 },
    { name: "Sleet Storm", level: 3 },
    { name: "Speak with Plants", level: 3 },
    { name: "Spirit Guardians", level: 3 },
    { name: "Stinking Cloud", level: 3 },
    { name: "Summon Aberration", level: 3 },
    { name: "Summon Celestial Spirit", level: 3 },
    { name: "Summon Construct", level: 3 },
    { name: "Summon Elemental", level: 3 },
    { name: "Summon Fiend", level: 3 },
    { name: "Summon Draconic Spirit", level: 3 },
    { name: "Summon Undead", level: 3 },
    { name: "Thunder Step", level: 3 },
    { name: "Tiny Servant", level: 3 },
    { name: "Tongues", level: 3 },
    { name: "Vampiric Touch", level: 3 },
    { name: "Wall of Water", level: 3 },
    { name: "Water Breathing", level: 3 },
    { name: "Water Walk", level: 3 },
    { name: "Wind Wall", level: 3 },
    { name: "Aura of Life", level: 4 },
    { name: "Banishment", level: 4 },
    { name: "Blight", level: 4 },
    { name: "Charm Monster", level: 4 },
    { name: "Compulsion", level: 4 },
    { name: "Conjure Elemental", level: 4 },
    { name: "Conjure Fey", level: 4 },
    { name: "Control Water", level: 4 },
    { name: "Death Ward", level: 4 },
    { name: "Dimension Door", level: 4 },
    { name: "Divination", level: 4 },
    { name: "Dominate Beast", level: 4 },
    { name: "Evard's Black Tentacles", level: 4 },
    { name: "Fabricate", level: 4 },
    { name: "Find Greater Steed", level: 4 },
    { name: "Fire Shield", level: 4 },
    { name: "Freedom of Movement", level: 4 },
    { name: "Giant Insect", level: 4 },
    { name: "Greater Invisibility", level: 4 },
    { name: "Guardian of Faith", level: 4 },
    { name: "Hallucinatory Terrain", level: 4 },
    { name: "Ice Storm", level: 4 },
    { name: "Leomund's Secret Chest", level: 4 },
    { name: "Locate Creature", level: 4 },
    { name: "Mordenkainen's Private Sanctum", level: 4 },
    { name: "Otiluke's Resilient Sphere", level: 4 },
    { name: "Polymorph", level: 4 },
    { name: "Private Sanctum", level: 4 },
    { name: "Rauryk's Telepathic Bond", level: 4 },
    { name: "Resilient Sphere", level: 4 },
    { name: "Secret Chest", level: 4 },
    { name: "Sickening Radiance", level: 4 },
    { name: "Stoneskin", level: 4 },
    { name: "Summon Greater Demon", level: 4 },
    { name: "Summon Shadow Spirit", level: 4 },
    { name: "Summon Undead Spirit", level: 4 },
    { name: "Teleportation Circle", level: 4 },
    { name: "Wall of Fire", level: 4 },
    { name: "Animate Objects", level: 5 },
    { name: "Antilife Shell", level: 5 },
    { name: "Awaken", level: 5 },
    { name: "Bigby's Hand", level: 5 },
    { name: "Circle of Power", level: 5 },
    { name: "Cloudkill", level: 5 },
    { name: "Commune", level: 5 },
    { name: "Cone of Cold", level: 5 },
    { name: "Conjure Celestial", level: 5 },
    { name: "Conjure Elemental", level: 5 },
    { name: "Conjure Volley", level: 5 },
    { name: "Contact Other Plane", level: 5 },
    { name: "Contagion", level: 5 },
    { name: "Control Winds", level: 5 },
    { name: "Creation", level: 5 },
    { name: "Dawn", level: 5 },
    { name: "Destructive Wave", level: 5 },
    { name: "Dispel Evil and Good", level: 5 },
    { name: "Dominate Person", level: 5 },
    { name: "Dream", level: 5 },
    { name: "Enervation", level: 5 },
    { name: "Flame Strike", level: 5 },
    { name: "Geas", level: 5 },
    { name: "Greater Restoration", level: 5 },
    { name: "Hallow", level: 5 },
    { name: "Hold Monster", level: 5 },
    { name: "Holy Weapon", level: 5 },
    { name: "Insect Plague", level: 5 },
    { name: "Legend Lore", level: 5 },
    { name: "Mass Cure Wounds", level: 5 },
    { name: "Mass Healing Word", level: 5 },
    { name: "Misty Step", level: 5 },
    { name: "Modify Memory", level: 5 },
    { name: "Planar Binding", level: 5 },
    { name: "Raise Dead", level: 5 },
    { name: "Reincarnate", level: 5 },
    { name: "Rope Trick", level: 5 },
    { name: "Scrying", level: 5 },
    { name: "Seeming", level: 5 },
    { name: "Skill Empowerment", level: 5 },
    { name: "Steel Wind Strike", level: 5 },
    { name: "Summon Aberration", level: 5 },
    { name: "Summon Celestial Spirit", level: 5 },
    { name: "Summon Construct", level: 5 },
    { name: "Summon Elemental", level: 5 },
    { name: "Summon Fiend", level: 5 },
    { name: "Summon Greater Demon", level: 5 },
    { name: "Summon Shadowspawn", level: 5 },
    { name: "Summon Undead", level: 5 },
    { name: "Telekinesis", level: 5 },
    { name: "Teleportation Circle", level: 5 },
    { name: "Transmute Rock", level: 5 },
    { name: "Wall of Force", level: 5 },
    { name: "Wall of Stone", level: 5 },
    { name: "Arcane Gate", level: 6 },
    { name: "Blade Barrier", level: 6 },
    { name: "Chain Lightning", level: 6 },
    { name: "Circle of Death", level: 6 },
    { name: "Conjure Fey", level: 6 },
    { name: "Conjure Woodland Beings", level: 6 },
    { name: "Create Undead", level: 6 },
    { name: "Disintegrate", level: 6 },
    { name: "Drawmij's Instant Summons", level: 6 },
    { name: "Eyebite", level: 6 },
    { name: "Find the Path", level: 6 },
    { name: "Flesh to Stone", level: 6 },
    { name: "Forbiddance", level: 6 },
    { name: "Globe of Invulnerability", level: 6 },
    { name: "Guards and Wards", level: 6 },
    { name: "Harm", level: 6 },
    { name: "Heal", level: 6 },
    { name: "Magic Jar", level: 6 },
    { name: "Mass Suggestion", level: 6 },
    { name: "Move Earth", level: 6 },
    { name: "Planar Ally", level: 6 },
    { name: "Programmed Illusion", level: 6 },
    { name: "Raise Dead", level: 6 },
    { name: "Sunbeam", level: 6 },
    { name: "Symbol", level: 6 },
    { name: "Teleportation Circle", level: 6 },
    { name: "Transport via Plants", level: 6 },
    { name: "True Seeing", level: 6 },
    { name: "Wall of Ice", level: 6 },
    { name: "Word of Recall", level: 6 },
    { name: "Conjure Celestial", level: 7 },
    { name: "Conjure Elemental", level: 7 },
    { name: "Conjure Fey", level: 7 },
    { name: "Conjure Woodland Beings", level: 7 },
    { name: "Create Undead", level: 7 },
    { name: "Divine Word", level: 7 },
    { name: "Etherealness", level: 7 },
    { name: "Finger of Death", level: 7 },
    { name: "Fire Storm", level: 7 },
    { name: "Plane Shift", level: 7 },
    { name: "Prismatic Spray", level: 7 },
    { name: "Project Image", level: 7 },
    { name: "Regenerate", level: 7 },
    { name: "Resurrection", level: 7 },
    { name: "Reverse Gravity", level: 7 },
    { name: "Simulacrum", level: 7 },
    { name: "Teleport", level: 7 },
    { name: "Temple of the Gods", level: 7 },
    { name: "Wall of Force", level: 7 },
    { name: "Word of Recall", level: 7 },
    { name: "Animal Shapes", level: 8 },
    { name: "Antimagic Field", level: 8 },
    { name: "Clone", level: 8 },
    { name: "Control Weather", level: 8 },
    { name: "Create Undead", level: 8 },
    { name: "Demiplane", level: 8 },
    { name: "Dominate Monster", level: 8 },
    { name: "Earthquake", level: 8 },
    { name: "Holy Aura", level: 8 },
    { name: "Incendiary Cloud", level: 8 },
    { name: "Mind Blank", level: 8 },
    { name: "Planar Ally", level: 8 },
    { name: "Power Word Stun", level: 8 },
    { name: "Sunburst", level: 8 },
    { name: "Teleport", level: 8 },
    { name: "Tsunami", level: 8 },
    { name: "Wall of Ice", level: 8 },
    { name: "Astral Projection", level: 9 },
    { name: "Conjure Animals", level: 9 },
    { name: "Conjure Celestial", level: 9 },
    { name: "Conjure Elemental", level: 9 },
    { name: "Conjure Fey", level: 9 },
    { name: "Conjure Woodland Beings", level: 9 },
    { name: "Gate", level: 9 },
    { name: "Mass Heal", level: 9 },
    { name: "Meteor Swarm", level: 9 },
    { name: "Power Word Kill", level: 9 },
    { name: "Prismatic Wall", level: 9 },
    { name: "Shapechange", level: 9 },
    { name: "Storm of Vengeance", level: 9 },
    { name: "Time Stop", level: 9 },
    { name: "True Polymorph", level: 9 },
    { name: "Wish", level: 9 }
  ]
};


export const cantripList = [];
for (const school in spellLists) {
  cantripList.push(...spellLists[school].filter(spell => spell.level === 0));
}

export const spellEnhancements = [
  { name: "Enhanced Ability", type: "beneficial", description: "While attuned, one ability score (DM’s choice) increases by 2 (max 24)." },
  { name: "Regeneration", type: "beneficial", description: "Regain 1d6 HP at the start of each turn if above 0 HP." },
  { name: "Extra Force Damage", type: "offensive", description: "Extra 1d6 Force damage on a hit while attuned." },
  { name: "Increased Speed", type: "beneficial", description: "Speed increases by 10 feet while attuned." },
  { name: "Immunity to Conditions", type: "beneficial", description: "Immune to Blinded, Deafened, Petrified, and Stunned while attuned." },
  { name: "Skill Proficiency", type: "beneficial", description: "Gain proficiency in one skill (DM’s choice) while attuned." },
  { name: "Immunity to Poisoned", type: "beneficial", description: "Immune to Poisoned while attuned." },
  { name: "Charm & Fear Immunity", type: "beneficial", description: "Immune to Charmed and Frightened while attuned." },
  { name: "Damage Resistance", type: "beneficial", description: "Gain resistance to one damage type (DM’s choice) while attuned." },
  { name: "+1 Armor Class", type: "beneficial", description: "Gain a +1 bonus to AC while attuned." },
  { name: "Arcane Insight", type: "beneficial", description: "Advantage on Arcana checks while attuned." },
  { name: "Mystic Recovery", type: "beneficial", description: "Once per day, regain one expended spell slot." },
  { name: "Ethereal Step", type: "beneficial", description: "Move through difficult terrain without penalty." },
  { name: "Quickened Casting", type: "beneficial", description: "Cast a cantrip as a bonus action once per turn." },
  { name: "Focused Mind", type: "beneficial", description: "Advantage on saves against being charmed." },
  { name: "Resilient Spirit", type: "beneficial", description: "Advantage on saves against exhaustion while attuned." },
  { name: "Elemental Affinity", type: "beneficial", description: "Deal extra 1d4 elemental damage (DM’s choice) while attuned." },
  { name: "Mystic Shield", type: "beneficial", description: "Add proficiency bonus to AC for one round, once per day." },
  { name: "Swift Recovery", type: "beneficial", description: "Regain an extra hit die when taking a short rest." },
  { name: "Spell Echo", type: "beneficial", description: "Once per long rest, cast a spell a second time without an extra slot." },
  { name: "Arcane Magnetism", type: "beneficial", description: "Advantage on checks to find hidden magical objects." },
  { name: "Mystical Ward", type: "beneficial", description: "Gain temporary HP equal to your level when hit." },
  { name: "Enchanted Reflexes", type: "beneficial", description: "Gain a +2 bonus to initiative rolls." },
  { name: "Lucky Charm", type: "beneficial", description: "Once per day, re-roll a failed ability check." },
  { name: "Boon of Fortitude", type: "beneficial", description: "Gain resistance to one damage type (DM’s choice) while attuned." },
  { name: "Aura of Calm", type: "beneficial", description: "Allies within 10 feet have advantage on saves against fear." },
  { name: "Arcane Resilience", type: "beneficial", description: "Advantage on saves against spells while attuned." },
  { name: "Swift Strikes", type: "beneficial", description: "Attack one extra time when taking the Attack action." },
  { name: "Steadfast Resolve", type: "beneficial", description: "Advantage on saves against being frightened while attuned." },
  { name: "Mystic Bond", type: "beneficial", description: "When casting a spell, regain 1 charge if the item has charges." }
];

export const disadvantages = [
  { name: "Attunement Shock", type: "detrimental", description: "Each attunement requires a DC 10 Con save or you die (and become a Wight)." },
  { name: "Potion Diffusion", type: "detrimental", description: "Diffuses potions within 10 feet, making them nonmagical." },
  { name: "Arcane Backlash", type: "detrimental", description: "Whenever you cast, roll a d6; on a 1, take 1d6 force damage." },
  { name: "Unstable Magic", type: "detrimental", description: "Disadvantage on concentration checks while attuned." },
  { name: "Cursed Touch", type: "detrimental", description: "Touching a creature has a 25% chance to curse it for 1 minute." },
  { name: "Draining Aura", type: "detrimental", description: "Lose 1 HP at the start of each turn while attuned." },
  { name: "Reckless Power", type: "detrimental", description: "Disadvantage on spell attack rolls while casting." },
  { name: "Fleeting Focus", type: "detrimental", description: "Disadvantage on initiative rolls." },
  { name: "Unpredictable Charges", type: "detrimental", description: "Charges deplete unpredictably, sometimes losing extra." },
  { name: "Magical Overload", type: "detrimental", description: "10% chance to overload, preventing spellcasting for one round." },
  { name: "Haunted Essence", type: "detrimental", description: "Disadvantage on Wisdom checks due to disturbing whispers." },
  { name: "Fading Light", type: "detrimental", description: "Reduces spell effectiveness by 1 level once per day." },
  { name: "Unruly Magic", type: "detrimental", description: "5% chance that spells target a random creature." },
  { name: "Brittle Construction", type: "detrimental", description: "5% chance to break after each use." },
  { name: "Draining Aura II", type: "detrimental", description: "Lose an extra 1 HP if moving more than 30 feet in a round." },
  { name: "Erratic Behavior", type: "detrimental", description: "May force a roll on a random effect table (DM’s choice)." },
  { name: "Cursed Burden", type: "detrimental", description: "Maximum HP reduced by 2 while attuned." },
  { name: "Disruptive Energy", type: "detrimental", description: "Disadvantage on spellcasting checks when near another magical item." },
  { name: "Arcane Fatigue", type: "detrimental", description: "Suffer a level of exhaustion after casting until a long rest." },
  { name: "Chaotic Resonance", type: "detrimental", description: "Occasionally emit 1d4 damage bursts randomly." },
  { name: "Inhibiting Bond", type: "detrimental", description: "Cannot cast spells of a different school than the item's primary school." },
  { name: "Haunting Memories", type: "detrimental", description: "Disadvantage on Charisma checks due to painful memories." },
  { name: "Mana Leak", type: "detrimental", description: "Lose enough energy to reduce effective spell slots by 1 (once per day)." },
  { name: "Fragile Attunement", type: "detrimental", description: "If knocked unconscious, the item becomes inert until reattuned." },
  { name: "Dark Whispers", type: "detrimental", description: "Constant murmurs impose disadvantage on Insight checks." },
  { name: "Unending Chills", type: "detrimental", description: "Suffer 1 point of cold damage per minute." },
  { name: "Burdened Soul", type: "detrimental", description: "Movement speed reduced by 10 feet while attuned." },
  { name: "Magical Muddle", type: "detrimental", description: "Once per day, spells may scramble, causing one to fail." },
  { name: "Vengeful Echo", type: "detrimental", description: "Damage from backlash is also reflected to an ally within 5 feet." },
  { name: "Chaotic Flux", type: "detrimental", description: "10% chance any spell has an unintended side effect." }
];

export const spellConditions = [
  "with a whisper", "while touching the ground", "under moonlight", "when blood is spilled",
  "after a moment of meditation", "while holding a gem", "when a secret is spoken",
  "when a song is sung", "when a sacrifice is made", "when a promise is broken",
  "when a tear is shed", "when a heart is full", "when a mind is clear", "when a soul is lost",
  "when a star is seen", "when a shadow falls", "when a flame dances", "when a storm rages"
];

export const quirks = [
  "pulses with arcane energy", "whispers forgotten spells", "reacts to emotions", "changes color with the seasons",
  "feels warm to the touch", "seems to hum a melody", "occasionally emits sparks", "reflects nearby magic",
  "shows visions of the future", "feels lighter than it should", "feels heavier than it should", "seems to grow in power",
  "seems to shrink in power", "occasionally vibrates", "occasionally glows", "occasionally chills", "occasionally burns",
  "occasionally whispers", "occasionally sings", "is Blissful: You feel fortunate and optimistic about what the future holds.",
  "is Confident: The item helps you feel self-assured", "is Covetus: You become obsessed with material wealth",
  "is Fragile: The item crumbles, frays, or cracks slightly when wielded.", "is Loud: This item makes a loud noise when used.",
  "is Metamorphic: The item periodically alters its appearance in slight ways.", "is Painful: You experience a harmless flash of pain when using the item.",
  "is Repulsive: You feel a sense of distaste when in contact with the item."
];

export const colors = [
  { name: "Azure", hex: "#007FFF" }, { name: "Veridian", hex: "#40826D" }, { name: "Opal", hex: "#A8CABA" },
  { name: "Garnet", hex: "#800000" }, { name: "Onyx", hex: "#000000" }, { name: "Gold", hex: "#FFD700" },
  { name: "Silver", hex: "#C0C0C0" }, { name: "Bronze", hex: "#CD7F32" }, { name: "Amethyst", hex: "#9966CC" },
  { name: "Jade", hex: "#00A86B" }, { name: "Sapphire", hex: "#0F52BA" }, { name: "Ruby", hex: "#E0115F" }
];

export const accentColors = [
  { name: "Electric Blue", hex: "#7DF9FF" }, { name: "Neon Green", hex: "#39FF14" }, { name: "Violet", hex: "#8A2BE2" },
  { name: "Hot Pink", hex: "#FF69B4" }, { name: "Sunset Orange", hex: "#FF4500" }, { name: "Lime", hex: "#BFFF00" },
  { name: "Fuchsia", hex: "#FF77FF" }
];

export const rarities = [
  {
    name: "Uncommon",
    weight: 40,
    spellSlots: 1,
    atWill: 1,
    enhancement: 1,
    attunement: false,
    meleeDamage: "1d4 bludgeoning",
    maxSpellLevel: 1,
    chargeCapacityMultiplier: 1.0, // Base charge capacity
    rechargeMultiplier: 1.0      // Base recharge rate
  },
  {
    name: "Rare",
    weight: 30,
    spellSlots: 2,
    atWill: 1,
    enhancement: 2,
    attunement: true,
    meleeDamage: "1d4 bludgeoning",
    maxSpellLevel: 2,
    chargeCapacityMultiplier: 1.0, // Increased charge capacity
    rechargeMultiplier: 1.0      // Slightly faster recharge
  },
  {
    name: "Very Rare",
    weight: 20,
    spellSlots: 3,
    atWill: 1,
    enhancement: 3,
    attunement: true,
    meleeDamage: "1d6 bludgeoning",
    maxSpellLevel: 3,
    chargeCapacityMultiplier: 1.0,  // Significantly increased capacity
    rechargeMultiplier: 1.0       // Faster recharge
  },
  {
    name: "Legendary",
    weight: 10,
    spellSlots: 4,
    atWill: 1,
    enhancement: 4,
    attunement: true,
    meleeDamage: "1d6 bludgeoning",
    maxSpellLevel: 4,
    chargeCapacityMultiplier: 1.0,  // Very high capacity
    rechargeMultiplier: 1.0       // Much faster recharge
  }
];

export const sentientAlignments = [
  "Lawful Good", "Neutral Good", "Chaotic Good", "Lawful Neutral", "True Neutral",
  "Chaotic Neutral", "Lawful Evil", "Neutral Evil", "Chaotic Evil"
];
export const sentientPersonalities = [
  "Arrogant", "Benevolent", "Cautious", "Chaotic", "Compassionate", "Cowardly", "Cruel",
  "Curious", "Cynical", "Deceitful", "Devout", "Disciplined", "Envious", "Greedy",
  "Honest", "Honorable", "Idealistic", "Impulsive", "Independent", "Jealous", "Jovial",
  "Lazy", "Loyal", "Malicious", "Mischievous", "Modest", "Optimistic", "Pessimistic",
  "Pious", "Playful", "Practical", "Proud", "Rebellious", "Reckless", "Reserved",
  "Sarcastic", "Secretive", "Selfish", "Stoic", "Stubborn", "Suspicious", "Tactful",
  "Timid", "Vain", "Vengeful", "Wise", "Witty"
];
export const sentientSenses = [
  "Hearing and standard vision out to 30 feet", "Hearing and standard vision out to 60 feet",
  "Hearing and standard vision out to 120 feet", "Hearing and Darkvision out to 120 feet"
];
export const sentientPurposes = [
  "Aligned. The item seeks to defeat or destroy those of a diametrically opposed alignment. Such an item is never Neutral",
  "Bane. The item seeks to thwart or destroy creatures of a particular type, such as Constructs, fiends, or Undead",
  "Creator Seeker. The item seeks its creator and wants to understand why it was created",
  "Destiny Seeker. The item believes it and its bearer have key roles to play in future events.",
  "Destroyer. The item craves destruction and goads its user to fight arbitrarily.",
  "Glory Seeker. The item seeks renown as the greatest magic item in the world by winning fame or notoriety for its user.",
  "Lore Seeker. The item craves knowledge or is determined to solve a mystery, learn a secret, or unravel a cryptic prophecy",
  "Protector. The item seeks to defend a particular kind of creature, such as elves or werewolves.",
  "Soulmate Seeker. The item seeks another sentient magic item, perhaps one that is similar to itself.",
  "Templar. The item seeks to defend the servants and interests of a particular deity."
];

export const staffDesigns = [
  "a simple, unadorned shaft", "a polished jewel at the top", "a glowing orb at the top",
  "a skull at the top", "intricate carvings along the shaft", "a leather-wrapped grip",
  "a metal ferrule at the base", "a series of small bells along the shaft", "a cluster of feathers at the top",
  "a winding vine pattern", "a smooth, polished surface", "a rough, bark-like texture",
  "a spiral design along the shaft", "a series of runes etched into the surface", "a small, caged flame at the top",
  "a cluster of crystals at the top", "a small, caged creature at the top", "a series of small mirrors along the shaft",
  "a small, caged storm at the top", "a series of small gears along the shaft", "a small, caged star at the top",
  "a series of small faces along the shaft", "a small, caged eye at the top", "a series of small hands along the shaft",
  "a small, caged heart at the top"
];